### ISSUE TITLE
Markdown错误

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#1]
## 课程导航+地址
课程9: 回归 > [简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/10a4b9d5-623c-474e-be81-fb1f33d08ece)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/miJT1JwhOSTaEXujIcBkfh7izyX3tj-za676BKASNXfI1Ej5Z6wOlPEucSZ4A4M2L9olRrF28X933kV7MpznReYDjsD9tCg961GO-HN3_OdCuzpqEMobDS8q3L1rwOdpSC8QaMg5cjPfABgZe81I0dwS7YG8KgDVuxNoYdZ8SPUWNm2xFD63JYte0t_rbuM_ni9rYPFK0AAarNC0Y24cgEy6vUqYFD4MRqW8WB8NtgbzpJ0lNouIMK4JyXi4XTKB5Sfc3Jh9av6Rj97bDW59oUGnDrpXlWRWJLii3dvjSvHq0sjeKL2n5a7CVvupHVizZdpWT-UvbiKne0_L1nW_wYpMq27EJ1d69qqjZRWozTD6cSikjoSaI0z4tahFCw3-Khipas62jM5zecvaNu5aMI7E9HpsJhWqjwvFXUPANbF4uH5-berpxvfwZ9Yb3d1lZPmAoDObJ4_qkWu3fXseHvINe6HvrsWNbcoY_9kqoQkeK2VlkVSs6vxSkoj2X8aUyoE9kaYvqOnjXaxbThuEWhhrzQYa3Ug3c5Etm1e5T1wIcfDNMy3i802rnTzQK0BEPVbZB_3QqkPVQ12cbLmK5dSYeT8PsWnynLgIOnxjgNgThJebnzFY4MNdFDeS8hE=w651-h99-no">

## 具体描述

1. 「在回归中，我们预测一个」的markdown把这段文字变成斜体
2. 「预测一个_状态」和「预测一个值_ 」中都有一个多余的底线

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
