### ISSUE TITLE
自然语言运算 > 回归 > 1. 简介 Markdown问题

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#10]
## 课程导航+地址
自然语言运算 > 回归 > [1. 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/10a4b9d5-623c-474e-be81-fb1f33d08ece)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46902043-201afa80-ce73-11e8-9612-0c8a0b79bdc6.png)

## 具体描述
Markdown错误
在分类中，我们预测一个 _状态_ ，在回归中，我们预测一个 _值_

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
