### ISSUE TITLE
自然语言运算 > 循环神经网络 > 6. 前馈过程 - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#100]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [6. 前馈过程](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/29a326a7-32b9-46bb-93aa-10a09acef7c0)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/9ebau0otLKxptebxqu6RO6FEpMEnZ3FMSCwWUcimr877EnByVMGXn3LdMyrYZ0DzZkqXNk0gD3UBv3020t5LKD6I36q71Sy3Va2O4fH2NRVEC9Xnq3WfCEv1K6hkQHuYj7e02XE3rlnm6kTs5_gc-uO_FT_SY86_xeUaF7Rv3w-YmhK97w6PLxvYg6lIBt8bj0TppR8Mo8Fhe8j1Adrup-tUfIIS3LtOcdKM4tEA30b7vw2VoxZvDu6mDYMBb6izmQOw3rgOFGHTNze2bcEgKPBCHQZCacl7TebIbw5OUubcfuFbt1elfZkv5CMRCNsFAUyrrrayXJs320yS3b1p8JHwdsXoPjVSJGz812GsWQ3Y_lvuO-XGpTMqxVnb1tqWKGrWdA9J4uSPaxwdvvyBw5Yi0WLz0LyjgmACMLjUud54U_KOmiUtZ7nrZSgOppNV0ikwy_wcGeU5dD2su22bYhPBPmZJYASqP-7BAC7id86-lVhsSIf0OUaRa0bUD00JUt-5IMkFzIbUHXcaR8h0M7cxztXHFOnEiwgwuY_htzxCN4DZtQpNkwrHkfvT-0lHxoM49NJqUEHybJPuhz0HvJDiR91g9YhJV4P0BLraDARxALnvCPPjHNMUtPpUKxw=w1600-h928-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Ip2uxtfO8UY3oOtufTXYK3o4R0BAbHvW4POksbKyHjCSqSSKgiYQIpxKkTCcvyn1lLM6GioM72EybRAG8S6cQ082y0eFC7ThcwyakF9vmYd7FsIS7XfNBL8HHt7LvwZ3_BQMROJGWg11lLJXA8wUi9ztFnNOW1HWIYjxqCOv06np4lzycVmZ-GLGTPBItoOg2lSjXy87L5o_i8tSdZJLrbY-q6BlvcbYPGGS0yG4aZEPq3l-YacafSw2_RfnZLdoT4K3kx-FLaIHGiuelUwwlFMci-Wu8e7N1y8uv4d5ENUf7JdRgndNg7u_DG2G9CQK_25Hr1trYuX7YuvMLhxDcdkZyptLTydvORZDP-1W8QLDVNuI6XICPk8YjB2kMluC_sox52FxcjZUjh3iQBrYLUllT66bMmIWeOlA2K3QBTU7AeGPMfgrSmR6AKG9VvIeuI6CP_TaCZzl2bCmRzvx8WFNPMCtJvjvTWQTmE1nOMbcpEtvkyiZRfgmonrakEDelKWT_BI_3Z4WySzZ-fFpZDgpRKJQ-j35eANIxQAPSHBdVHheIqVNWsOqsGQSKrBYgxS0K6Y8mP8oftYue88dOal2EFwtradkcZ44onwmQJ9o6O_quwZGeSXtrZcxpOY=w1582-h914-no">

## 具体描述
视频2m0s~2m1s处字幕「x1 x2直到xn」和「输入向量」，建议这两句合并成一句「输入向量，x1 x2直到xn」

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/zs7fr-HHFDVHNWX4AozvmH97VbZNdVjj9fN9Z3HrFa7yW8u0OuVXoChHzokgMnkbZATXQ8SDPJnoMJSvJBDYXXhwpv5APgKy-UKAUQH4fd4PMR8HJZiStdSTi4dZZ11EB5FqaFu_Wne6V0Q9MbBrKga0eC5Z1C6NjdWtb_P6EPoee5Jns6Z8YCm9X0j2z-yeOBlmZYnUdpuTFAGe6Ju2EonfdTlgzvzwvMwHq_yYMm_M7FX7QpQPwKp3Oa5Y27H5R0JBdwoaCeVYBPFUj5eK7jEre5wF6fezT4oHXJzLTgIXsUmd5Dmi7-c0o_gjLudOOim0jZwh0SPFpXRTufnu3JN6hXa5te8cV4dzHOCQGFogL2F7loAElGe4O9TQMiQI9nGe9dR9MAt4x3SpzZA98m3HrT6LiCRPo53Xv6tey6YDjOR4oCmKsvF8_XRcBJ-F26cR2TwKItzpetYH4Wqj-9_bIDP9TTdCdUm6O32A-_8ho_ZCTNt75nwA3v7d3B8FNnAiiIxZM4j2zx3zdxvKEykTAPpp-SQBLfAPwxLE-K_YdYMt9UvPGeJ-2QqRSHJ0ZuPPyiYltkZvU8votlo3rI-UJzP3kVrS3ON92xYLKSZSPeY6G1EVoF_QaqJHL_M=w1604-h922-no">

## 具体描述
视频2m41s处字幕「暂停视频 在你的注释里写下推导」，建议改为「暂停视频 在你的笔记里写下推导」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
