### ISSUE TITLE
2.自然语言运算 > 2.主题建模 >【7.练习：选择主题】> 字幕

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#101]
## 课程导航+地址
例子：2.自然语言运算 > 2.主题建模 > [7.练习：选择主题](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/2a9657a9-56bf-4859-911c-7cc8e517bdb5/concepts/6cd6633a-fa53-463f-9a8b-0ff8a876a5ee)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47090730-06ecc200-d256-11e8-8a43-acee9b93ae77.png">

## 具体描述
根据原声来看
视频1m15s处 英文字幕：0.70 改为 0.7
中文字幕 0.70 改为0.7

**Comment by yifangwang08** [comment]
感谢反馈！

**Comment by linglu** [comment]
> ## 课程导航+地址
> 
> 例子：2.自然语言运算 > 2.主题建模 > [7.练习：选择主题](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/2a9657a9-56bf-4859-911c-7cc8e517bdb5/concepts/6cd6633a-fa53-463f-9a8b-0ff8a876a5ee)
> ## 截图
> 
> <img alt="demo" width="1212" src="https://user-images.githubusercontent.com/33828759/47090730-06ecc200-d256-11e8-8a43-acee9b93ae77.png">
> ## 具体描述
> 
> 根据原声来看
> 视频1m15s处 英文字幕：0.70 改为 0.7
> 中文字幕 0.70 改为0.7

你好，请问主题建模的 workspace 还有么，能否发给我一份，感谢
