### ISSUE TITLE
2.自然语言运算 > 2.主题建模 >【12.主题抽样】> 视频重复

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#102]
## 课程导航+地址
例子：2.自然语言运算 > 2.主题建模 > [12.主题抽样](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/2a9657a9-56bf-4859-911c-7cc8e517bdb5/concepts/b52049d3-55b1-4670-8fc3-dcd19ace7365)

2.自然语言运算 > 2.主题建模 > [13.单词抽样](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/2a9657a9-56bf-4859-911c-7cc8e517bdb5/concepts/81b2c083-c64c-47c0-acd0-25da214b247e) 同样有此问题

## 截图
无

## 具体描述
该节课程有两个视频，但视频内容一样，只是视频的背景不一样

**Comment by UdacityShuwenLiu** [comment]
已修复
