### ISSUE TITLE
2.自然语言运算 > 2.主题建模 >【18.后续学习计划】> 链接打不开

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#103]
## 课程导航+地址
例子：2.自然语言运算 > 2.主题建模 > [18.后续学习计划](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/2a9657a9-56bf-4859-911c-7cc8e517bdb5/concepts/6b1e4da1-cfec-4832-8e63-ec48378df4c5)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47095994-e1b18100-d260-11e8-87a8-d743c91ea5d6.png">

## 具体描述
递归神经网络 (RNN)、长短期记忆网络 (LSTM)
这两个链接对应的课程都为英文版，导致没有权限无法打开

**Comment by ChengGoooo** [comment]
#131
