### ISSUE TITLE
自然语言运算 > 循环神经网络 > 8. 反向传播算法：理论 - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#104]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [8. 反向传播算法：理论](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/6fbfd066-6907-4f72-98b8-c5743818fa06)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/sBsyy8iEKpNcEaVhvwwUPhR87i6lfRKeaw3sFWxIsBrHlluhJhs7g5H2sxWw4CMevrB4kEjL1i8qcvQNWGOBLKN6IbmfAlf87gJgQtw24DTnGqXQrhgYgz-wRf49gVpgclmwt2hyXBzQspbp01d6-PSe-F6d3BiK9euH_M3Z2uZSFo_fVkucVEwzXgBVxzmBCYrcCgfzEbR9b11SewCANJjjvmQ47pLT75xgcqgmO2XpRawvO3gFZERET9YeenpwktfIJPhxJJuB_SljkmbytbhLfGDlnFFk9y2RbGDAJlyMWQ9fhjxU9n0ykxoHxgtAG13bFuC_m39njyaivpSqjVp-HoK_RhuXHkAddcLukJWfXzGk6rjOv1p90Xr11i740-mQwZDL0aFr8u-pqkS7_gy04nIFkQ4aXbOwpqzjGkaFvmMSsI8KPDIs9XFUlElLC38xY80W-wYITivWpYeXUBpN_-4pv4vHcn7nZKWlg50B2uBETolwpGsG6LIVZ9dZ-joiYdbNy_eJ6LC2L_hjO2Oh0J1bc5kjqJPtlcGt2J8t_eIb09fGmeBCpHXzWfayfU6KdKFFJl5Wy_kN8IFMgUokCZ75-8Vyrr4Upv87mNVHzdHHFXIdlJdgtfEdDE0=w1576-h908-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/WVqYUd16o_-PevQNNswVBuCbjPk21uyaAAO-Ap50ICxpXA5lXMLJG-qFY4rGratbgRsQ-iuVyebnoAca8s18X9rAYbs1h1ziIdqotGK4JiX_CzfkfvvkbUu6L5YglvWRxz3PfmQ_QjQfPq5lqGNS9W5CHF03teKPO3Bkofel0kugnWHk2gv7zRAE9UXUY6SdKdMdGWJY5rmwPxM-TsTShvDP3hqHkloHNerwuVXgbKnUbZwnxJiyOOiSpRN_qNSDvAv9ePN6ZtsyUvK9N5ivUKz0oTI5wOqsohoM2iXpgohXUvFAdIBqJk7cHRVKDACiG5t7xswZeGyA8u5wQIv_Tansr45z_PMehG1dY_xHAa2qcBRe5NbszTT7Tw6ML3vlQuJVM5kQbnZ_ykDC_wOcNO1a1RuzqFvG8mZPm5XV1FiXjmegZhqF1DH7XM20AShNhhnxgmoibQuClEzb6YREl7WbOfNDFVSNgFOzi0tarlsLlnoPiBHNz945347rxP0fgi0YuDrB-QGMmxMX7dAz9Y-qjIkXYMkZFoHSR08_N9PBjqFLDgkC6tzANA0GdgDRdecJz95WapsVcty5Uf3E9hTCEmcfj8_ipGYF1o6XcCAnNTwuqoFKZyP7RzohhFk=w1576-h904-no">

## 具体描述
视频2m18s处字幕「你会发现接下来过拟合部分」和「一些问题的实际答案」，建议改为「在接下来讨论过拟合部分 你可以从中找到关于这问题实际的解法」。

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/hjHbgmga8WtJpShDwbhpT7xuQ0LknHk_O-aweb2tMQ2BXqQC8GxR4ySwHm4TDYvjvXPNQ9nO-P0WIss7CTeLfL1LTtpheNbIH2buhZTDeqVugC4EWEG5fud_GSIhylD_yQfX0Jk4qpcNBMI7qjnd8bOJshLnPV9uwETkkPTNwd-FpKfh7RnPIAXsrE5Uk9dxwP6pnA8yJikcvuieBoL_GHxYY_hiGv5IGvSLGLeZ0HJ_bR5dhXoLPaSgn2LABK--LDQOTGpLZqbB7VntTzP54VZdAi2XeFOLdGPH-Nsw8BnK0JjrjByLuDV5AoNzMXgrQ5MTlelwiLrOT_YsdOQLSyCF_3pzBTi3wWs2KoATh83UbkVnOPwPjmG2o84uODepAs_F4MXQjtPYof3FjBuo2eNWCygrp833O2cbSCkkt4sxEkNz2z1uHK4Qx3HtMvEjtIz-tC2YiELOb6t9C5gVQmkG8RPzD8gNu23CNMxORMC27jv_M6-1zY3Sjgt31SWEDAod0dDj1oHdPO6HXrV7kL06NGp0kMYiuKESQUP79p7URdQqZApdrJfjLbDe48R26V8IrlXsE8aEYSxS0nquWTgIBj4gr9E10HUmXks7kLBJJo2rR5iemQKVOEyWiQY=w1302-h124-no">

## 具体描述
在内文中的「训练神经网络」有着markdown错误

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
