### ISSUE TITLE
自然语言运算 > 循环神经网络 > 9. 反向传播算法：示例(第一部分) - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#105]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [9. 反向传播算法：示例(第一部分)](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/00d69708-34de-45a2-a93d-4213f0cea51e)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/CWCaEDWuHtvmAHag17rMRFeHlQvrHMxKdqXAnx2-R-1n4eW5N_HCE4GCN4TEuDXtTU38Y-tiXCADfPBk0RVlXWayx7g_AQ6K0_3QniNm7zgjW6FKykOz5wjNWaJgcpdtapC1Hofjho38PmE6d-FwlGOmqbJKTmWba4N4xGXMuKowQNkxCSiLrZqtJoR19Zp3XdSDvCa_dkEv-rhp4H7zGGKuI7wznHWXhSETERhEy_Y-4auSsCWkPt5thAG5251QyleKi5vvjVzj5lW73PA4phmXPn4xYi-E-z-5QJGv_tgGGPC-mnauNet2VXRV2-S6Dhsi8u3RA4KtKlAV3WTap3WVz3d70QDajwT7OXXKjZoQdur8FuzRmNj7rGypR5DSMLQhI0XKP_vaZg3ANfRZHuhpLkx74f5x897q9cSqexWwuTmNy-_-kWth5P-AvX01WX4q-CfCeq0QH3KySkDvDKvcck8joxPhWLZW7luT-wgbxNJFwP7SEGzDzy5hbRQjSceX-1DNn9PVE0J4dtYEbPRuCBpflwPZiHQhAfyoE1_OO70q6fVRl-NIo8lw_FHu88823xA4yNZ1dAo4deB3urrOin7TEajlqmqV1ak2mEZzxKdkQvo_oUsyFFuGc7M=w1582-h916-no">

## 具体描述
视频41s处字幕「不要忘记你的笔和注释」，建议改为「不要忘记你的笔和笔记」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
