### ISSUE TITLE
自然语言运算 > 循环神经网络 > 13. 循环神经网络(第二部分) - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#107]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [13. 循环神经网络(第二部分)](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/37e5c026-5ec4-44ef-b3c8-ceb1c1532b8f)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/q-GvrPrCxzm1c1c9y5ZL5jczp871QmDjtZu903RnIdYN9mLxIxTk7t9DQFt4sbXLg_L4NlAub_hsNO8ZPjEsDS3HvXB0NlyepM3J6LLbBp8u7-5ouP0gA_NK6db5xPomxGrHEp7eZKVKWo40N_qSVH8CkJ5oJ_l6hR6PTOEoZ5YnIvKE7ym1fi-WjWLDs6VPpjW3x_HVUc2kpdfiTdTj-QKGNViFaFPwTMopJbae8TS-wJlMIVsz36bG0GA61hGcnyEMgLX0OQfH0-9m86v59Bmz0JFiwuU72lUIsLpHj8tt3a9HzWHg--6T2WC3is1NKd8LQRgi-Q1sOrjkFdYFQiKRyWL1s_aqcPcbKlUrfkk0DlnAe_w69zBfFACUppkK7B9EtdztB3sifkMejDI8wQj4IZ6fqy8uRbl884laMUZOOwZ1fkXIb5Hyqj6UkfZyOD0KauF6iK-Lq-RCuRRXZqdhh_IEss1G9bRyluxDhwXMppXGEivJJpS3Jnu7U5KIH6gPevFTGwpd6M3ef1QC4cmRJk0rDdCjC6ROdN2C5H7MdbO45ej8CDaaeACEZFNTtj1VrathkR9KHDznr2pDnVu4mUtkbp_oSoeOqVPL1uycadjWOOJhzjzDZcdDJhA=w1590-h902-no">

## 具体描述
视频35s处字幕「T-2等等」，建议改为「t-2等等」

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/KbJvEATsf_LQejTDeZKckSm4V2tEvuCrPJuJ1i-egQPAe8rpe2Syn7QMLE97rBSUIP1e8Qs4g2-EA_8kjY6E4aqWcKyBJDJNZJ9Ms-xc8mApewvfYZCmoV9NMVyHsDhehMWHRD9dHD_RxoFoyeUkPQ-kkmoIRKrG-RK8tqP-BV1HRlBZp97mCnzleSSGsPBNh9EavhN3Tkx36Ak-iY3GkV6Nw8RHQ0Ql2gAZVUnjO-s8Jo9YCBPA4H6kBFFoYiC-1dhdPfaN_Bd34TxpkJjqxakC02NPWqs4LEaOY0piYoEvYoU5-e7a5uIqEMeiT1UHwbuVdIrOte7ZVWqXtyLerOuFNC9FxGuZupRN27EYT04m9QJOo7JF_yZ6FF8Aj6QQC6q9gErxZQ_ypXF-CawTNl5i9YfnT_Sd-dgTHrH2KRGxJtO7aMLkhnvTR2Zn4uSVLjZZU5c2kytWwYXSj0TXyUXbsnnPDs_m5af3bSkyQFfSw21saIU8CT7zAh3vA2mG3GFcGQpn6gBhFdV4_wOvK5nmuhAkOeg21M8jFmUmVbtHDLcXxEocP9QEH7i9h1CjSVWP_HHhUHxDdV7Xl8BRiPGojfZblZ0wcEPZVcvVB7O-HUtgnE5CHbmr8nIm1JE=w1592-h914-no">

## 具体描述
视频1m51s处字幕「取决于时间T+2的输入」，建议改为「取决于时间t+2的输入」

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/YpgtdpxFxL6uKD4cSWOp3Kua1Qs8LhQTcSQTuZ3rcvas27_kcc8Np9SMMw9L_tnm0YDc-xTcufuXn_pBUsg2yYJzSdd_cTJt_WNDA-2bVa07G271nBJVcXIlU_fAyEOP-RYat-K1fPVWL2TXNvFHKueEhDcZpBeQC3p0PGOZSXHuGZfKrS_7AFdLAR_Ttbnca3O8V4FocKMtpSW9DWXXESdWC10rlnBACSb423uMeO0EhduezuVUjmdlJEp3QDH1DPvxz8Xfe5ujqQTyYIlPHqqW0A9kGclt2DgmByR7VTpQ7F1Zxrq9La-ALCnkSyzErx7wSOIsbT7m1VQrQuABWaDHtEUOK7DgCR8e37AL8pAG0_r3nETJ5fJitM7LdF1S3jJ-CqyNfQPWwX92tGOxk9dvzu1m-F6UxoipyDVeLXqIf_Ml5ktyY3PjCGzjQQQxcT6fU8ePqDXgH2-toxM7RJzFK_diXENY7E0b-kVZn2FJYsoYISNWRQsBGtR_lW6H6bj3W7FQSJ7ADuk0Y2JmFTsfknaPi-xJRjUCBRZ3GPNkdZaopxppv5bqjysuRf4WqCiuh9BvM3oJ_Zdv38yMV2SuDsJOZnZ8hsfayoPKTQpCN5H_kwa7sEbctp8ryRQ=w1576-h908-no">

## 具体描述
视频2m33s处字幕「不过存在轻微扭曲」，建议改为「不过存在些微差别」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
