### ISSUE TITLE
自然语言运算 > 循环神经网络 > 14. 循环神经网络：展开模型 - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#108]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [14. 循环神经网络：展开模型](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/25ec7155-a508-4bfe-bbe4-6fd21e9ff4fa)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Fsj_0Ww0o9Ocgi-99NGZG6tdWIn37a2l3R4DNAIIdlWrnGNiHjVQrIiqnVExYfqd3ZJok2f4474P4bP4eSxLHQ4-kqET_yjk2b89iRybSna5jerAdjP94QM5EhrhnpP7izrN3Vq-KFoMMa0iVuoVTinInA-mYEOZQDP-0vbL34EQ7x6g8FETk2iWECLzoHQumOl2Vt7n80kYuLXm7X94YXTRm524HAkX6DMH8IwrHn53lJwk5jyrtprqKWaayXCiIbI8faIr4dbrgp_w_ezmerlG83Ne0i80rLYo8Dywr6X0jBMKURD_VIuNCxwWVinXMSNYRi5kIRJ_8FydHnGlj-hZFVkEPrQhs90r5NtOgczm97vhgEZMqrqOBKRRnTqOYavLdCJp-NXQjPVz9Z2qiWDXqJ-jkm4KyZX3kO-CSM1HJIwCeq51E0WSNaS5Dbmngdg4GhDLBMa5ZQ6uvKnZH-hqZIPsFUt-YIIRfudMDXwbPEM1CpOCDBQBFotI_0DElOlHi4njWLREHz9CzHmdkam3IQL14IiWBr7WqN27mmzB-g6RAH1i7NU1ERR03R6DA98eRAWSB4_bFqTSm7kxo6sJ-qwKMAYYx61AZy18oemVg_4iPBOb4rOBaeU-U2o=w613-h354-no">

## 具体描述
视频1m3s处字幕「权重矩阵WY产生输出向量Yt」，建议改为「权重矩阵Wy产生输出向量Yt」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
