### ISSUE TITLE
自然语言运算 > 循环神经网络 > 16. 循环神经网络：示例 - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#109]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [16. 循环神经网络：示例](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/bd7af2d0-39a8-436e-a5a4-356f04ac8556)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/icYPePNzr8lBn_i5S7a7dWviSvOuKNXaaHVPYSo5oMSR0mM1nyAOMYwHCrEm8thN3l68Oo5zezZmOQIal3mmOTcnXe0aybK9ZEOe38bsKxeNyl2VMl74Zp57gNDlF9db5JHMU-ifp_9vhSJ3GQmsmFvo6fOyVYVWWLhbX84OLWnF9Ev7WGGqRO71M3Yj3wvOn_UL25x0V_98AtMfnhH5P6SCgju3ouVISLuJla0saAHy5-Foq2Fq-d9hMXuUVPQMk3zZcBclDBBCJeHi65yCGJpoIxRin4wOfswfay2EtsNSRrTwALOmgTup0I0c7aINlAVIkcAZzWGlFsmtXWNf2qOImBLrc4OCHnrWl3APYtYeC-JVZdgc92DP2c_Qldjn_erOilqdAQjUjCWWWGSSP-Q-qmm8GpdBUmYKyAxoA7hp7ZmjNCId0c_56RI7_yw7yRd1HXqlRhbbRLawvGmSz5avEe6CriPJSQtojAseUYakuiDTR9yWTtZfiKQE_GXTspHfOj-gea0H-3fNvjpbnk7g9sQQa_8KXmnL2qZ-QpI7dxsrRiLyGTTZortoGwkeTMeti_D_STnqD_q1zf9BuH92nwT9r-80jOcSLSzX34eWfXysWJ9I0sILzA79e_E=w1580-h918-no">

## 具体描述
视频39s处字幕「这里我使用的字母按照升序方式 不过顺序是任意的」，建议改为「这里我使用的字母按照升序方式 不过字母的顺序可以是任意的」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
