### ISSUE TITLE
自然语言运算 > 回归 > 2.练习：房价 - 字幕排版建议

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#11]
## 课程导航+地址
自然语言运算 > 回归 > [2.练习：房价](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/12f6331c-0bb3-48e2-b0a2-31f852e117ca)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/0OD6wvBEYeCCaTQZQZiGVaegu88Bm0KBfPpnO6MMtSAAjDuoJFcl1hd8t0rLB14qlRucWGEapWWPTc5mJ255xSUuyaAYyvglAhQCj-q2uwLn3GJh9i8rz6NzOHKi_kH_DBSuecB24eGPh3S4EPTtBwiZYHP88YKAeciHZje9ITqbi4SclsitaYaSG9v5eTQfWCZZxzvd_14OVcuAou33aqVBpDf19ocTyN9dc-Ey5K-6kFuNDdUf6Q2JxdDUvpM1M_GtFYCC--CGVF9SDO0T6-CzwQagyqtTkeCL-CmfSK-0SSDPfOcdXe8DTWl9dkorQfuDka3okgsfVOZYxV6fCcdcZQWsO-rppwrvEhCcIPxSZOGUYpltYSA5Y5IL3E-6hHoGVxBqKGYZURKCg01wFB9__18IRoWUXcFCVlgr3IW-SHqkkh0rnnDgTsWdlYEF_3Wvx3ExrdR5H65CNj4ipTO7J6O8QSENaVfOq3njyWHi4bC8sjgCu3DpAOuJkBXHXte5UM4GkzQ_nIoTLpjvhD_dEDFKU8a32CFIoTGpmfDb4e9qY9nAdwNKuxT89B_Mmsz63mUA5uqBhYE3DfNqpO_C5Hmjs8HnNbh4BnfA7B95SRqOoAyJotbAnVBzs8c=w1624-h884-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/KmekK-fEuyXQezvi8OKrJFA1D3BrVty42DB8Tbj8tICVCvBmRSiTOt-J-m4WTZhpIe1di2cBguGEtqGELstskKpwR9N6TuRZ15ARxx0x2-qhRJG18UhCi4l2Pp3a0q8ooSS6yCBkz_h1gys2Ke1xHUH8PKFHgDSDkkfCezq7n0sxt6lxKeuBHUKr6_3rmOLE1NrJLntG0DcGNDBBDfT_w_gpHJNN2RCa6GtT9JkJ8I8BpPmwzkRDXCnRkX1afECrZAs_hV8gh5FI4bGcaDbBMcraBpAaK1csrClDsXEOvd4fiNZTrWtps8I_XpPgnBT4go0Wb41khWlFe7-aymkrxucS-xYlXv3j7QrQqTIOdGXBaGBaUjX4ed-8MUgZqDZLp3wdHuZWCAYEecUXK4KbCM8qItV30IvJPUPIdGyJqOhKnzDn6mDDKEgWIQxAiFr9Jsi3L9Pa1-W-QHMykbbO-nXUmd9XpSzK-sEBxaJBSD4RMy2LGtHsJVz5Ut2PAHrvGvrjYJR5wYl0ILQoL3ueUZ7Xb8nqSh8kQtkTaNHhV76o-y4oZeCXyOXvSLCj5XMK2zE-kaiBysM1IbcAtwfTEvGdiDeNTSbuYDRpJwRAi4U68GC9nkqIp3qLESCgiE8=w617-h332-no">

## 具体描述
视频50s至54s处的两页字幕可以合成同一页，不然会造成第二页的字幕消失得太快，会需要一直来回切换。

**Comment by ChengGoooo** [comment]
Changed at https://github.com/udacity/subtitles/commit/b7f44d9c90e1f3d6794d571974c4c0cacd1c2a72
