### ISSUE TITLE
自然语言运算 > 循环神经网络 > 17. 基于时间的反向传播算法 （第一部分） - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#110]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [17. 基于时间的反向传播算法 （第一部分）](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/c872c9ec-18a9-4e3c-840c-b9fc85c93641)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/hpqUuznvzyePHKM0WNJPJ9lxFKzjPUCEukF949Wc2EI4TZIggw4F5NUDmZBMZcYnraGKV4TXowisPfuz_eAWD_YATToBBmF2BU3OeoNWca-VzbUHdY7CO9102xj1lECgwLbjdit8xFUJx0SOGQnxOy2ue3amVbPmYldmt3SjBP2dOLImJlN0VQZxG7QmMuDogkS5MU9ECHZraVzGH_2QVy-zRGIwDge2vxVLzvntlYBZ_2knyo3cj6q0ixYhupr6gccCNSgsYpPzMTACWR0Q8wqqmXJlejra_Qdu4jwMjPsRnbSvMmJupuk3PS1VL2kqT7h3IE3QqfaM9kUrYLzLm8yDl3z6v4kD7akDNqoUJhagFWSbMu86TMEd4b5aaw1OKRi8bv5UcPq2RMh0Ugp_s0ZrmPY38SlGQGMZa2tpMCSgVHRq009DwkQDRMaiq4oWIg3wh_0PDdCsD1NDiHpHGljui4-zvDJBUYzzbiD6cTGebcs0z6iEVdu-xyv-RWg7OEjFTnuplyS_UPr7grnrJx3IpYKlISnsxLtAKTm1WcgwnzLmuvUdD5YVF52bkT_0NtLl4pwiqSDJzFnziaNRAMHNEzn8J0Tc3UwJxNa6QQIRhrZn_vmXQrbwb1-UaKQ=w1604-h914-no">

## 具体描述
视频18s处字幕「反向传播算法中具有轻微改变」，建议改为「但其中的反向传播算法中具有轻微改变」

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/RrBo_kBALMaMvB6yTRdHeu6fXmFZG_L9huaohrhFpMdY7oKM9kLNymZCUI5xYEOrqIW8Vk8O5tMoPpvaUBg_CqJvLmSZKevzVuA4HY_-WsGtlp_94JpSziyMVMXC9oXggySU1pK3G7jIIsTRtC8qeINUsuwmn0VecOHWhdqlYhFrPMdMhU7F-Rrt5CiPpBWlEHNGL0u6e3qwQxEvICfth9e-KWyJvzOde-7T9qhzYDhayMsLRR89NxF6Bd75hzs9kcZ-x7To2Rq09JPvyPYcZMzDTcM3jdKhD0vA65LlgKSW8S8wA-u0RdNlaXaAAvntK220h5QPISuZHaIMVRTSxliSQ2RbwPPOIaEIE9sUPB3GBWt-qNLJiBGF5t-Iinepi875Zgjl3tVZ6G9Kl_zH6ywBWXQyGkm1oXNSh1j0p_KO29pmJfwQ_0bGyop2ay4RcHxKfOZXAsYoOXxrfOzyr15bN0AotW52IUYytUD_15-4cAom3coUOtDw99SOZApqKJSFxSuPXhjgkxLW-fELUqMB-_6a6nEEyFeYFTUAscuCpeef1OTBldL5hyW7NP3rzaeTEkGYyRqsb4uB7YHZRUg4pw7jZxoR31LfIa0FezpnXrzz99-zxW0L2yg3wU4=w1606-h930-no">

## 具体描述
为了一致性，视频1m1s处字幕「通过应用激励函数」，建议改为「通过应用激活函数」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
