### ISSUE TITLE
自然语言交流>语音识别>1.简介  字幕翻译

### ISSUE THREAD

**Issue by Sampson91** [udacity/cn-nlp-issue-report#112]
## 课程导航+地址
自然语言交流>语音识别>1.简介
## 截图
![image](https://user-images.githubusercontent.com/7878063/47262656-6e8a6200-d521-11e8-92fd-c97631f726cc.png)

## 具体描述
视频1:11s处字幕 The twist is that speech is structured in time and has a lot if variability.，需改为:语音在时间上的结构的转变存在非常多的特征。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
