### ISSUE TITLE
自然语言交流>语音识别>9.语音学  字幕翻译

### ISSUE THREAD

**Issue by Sampson91** [udacity/cn-nlp-issue-report#113]
## 课程导航+地址
自然语言交流>语音识别>9.语音学

## 截图
![image](https://user-images.githubusercontent.com/7878063/47263308-b4e7bd00-d531-11e8-8e17-9ad97a480f3c.png)

## 具体描述
视频25s处字幕:字素，需改为:相反：一个字母

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
