### ISSUE TITLE
3. 自然语言交流 > 3.语音识别>2.自动语音识别面临的挑战 

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#114]
## 课程导航
自然语言交流 > 3.语音识别>[2.自动语音识别面临的挑战](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/bf895442-7584-420f-a9ac-324dc5af1160)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267190-058c0400-d58c-11e8-8ace-10c8b82b21c1.png)

## 具体描述
视频56s处字幕“ASR需要知道” 移到下一节字幕比较好

**Comment by yifangwang08** [comment]
感谢反馈！
