### ISSUE TITLE
3. 自然语言交流 > 3.语音识别> 3.信号分析

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#115]
## 课程导航+地址
自然语言交流 > 3.语音识别> [3.信号分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/71b0adfa-7242-44d9-a4f3-c8a1a7743961)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267230-d924b780-d58c-11e8-9f9c-44c6f7f144f7.png)

## 具体描述
视频1.20s处字幕“我们可以用傅里叶变换把信号打散成这些成分”，需改为“我们可以用傅里叶变换把信号分解为这些频率成分”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
