### ISSUE TITLE
3. 自然语言交流 > 3.语音识别> 4.参考资料：信号分析

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#116]
## 课程导航+地址
自然语言交流 > 3.语音识别> [参考资料：信号分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/f95ecbe2-64c3-4317-9038-882b09156d52)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267312-ab8c3e00-d58d-11e8-9457-803f22b2afe6.png)

## 具体描述
建议增加一个超链接，介绍“频域表示法”

**Comment by yifangwang08** [comment]
感谢您的反馈！我们会在后期的课程优化中参考您的意见
