### ISSUE TITLE
3.自然语言交流> 3.语音识别 > 5. 练习：FFT

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#117]
## 课程导航+地址
3.自然语言交流> 3.语音识别 > [5. 练习：FFT](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/e4c7874e-ffc0-47ac-83bc-6082a80540d3)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267322-d37ba180-d58d-11e8-87bc-0d92cd8f125b.png)

## 具体描述
下方缺少超链接

**Comment by UdacityShuwenLiu** [comment]
已修复
