### ISSUE TITLE
3. 自然语言交流> 3.语音识别 >7.参考资料：特征提取

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#118]
## 课程导航+地址
自然语言交流> 3.语音识别 > [7.参考资料：特征提取](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/c15deb5a-7e36-4909-b09a-1e7d8cc2915c)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267355-716f6c00-d58e-11e8-8838-56992e5c22ce.png)

## 具体描述
页面无法打开

**Comment by yifangwang08** [comment]
感谢您的反馈！经测试该链接可以打开，您可以再试试。

**Comment by UdacityShuwenLiu** [comment]
已解决
