### ISSUE TITLE
3. 自然语言交流> 3.语音识别 > 11. 练习：语音学

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#119]
## 课程导航+地址
自然语言交流> 3.语音识别 > [11. 练习：语音学](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/55d0af08-cb6a-4c9d-80c2-b646112124cc#)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267373-b85d6180-d58e-11e8-8974-ae143fb05aaf.png)

## 具体描述
作为第一语言非英语使用者，这道题做不了…

**Comment by UdacityShuwenLiu** [comment]
无需翻译，谢谢圆圆
