### ISSUE TITLE
自然语言运算 > 回归 > 3. 参考答案：房价 - 翻译问题

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#12]
## 课程导航+地址
自然语言运算 > 回归 > [3. 参考答案：房价](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/eb2ba02e-e89f-4973-825d-5eff662071fa)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/_kyW6DbJ3XDgCiAJf5HY1jv_8e_RbgMAxVLYhpwMSYudB4pxPcmZEagMu-4ZMp3BzKZDwJVDTXjtdZexNHhuPy5XRuy64nz6hLoXa_ba600t6c2r-zydInw9rBgYX80QiHNybdIXcIHrb230azqqWcn2gB8XriHOoBNgiEhxj-B9zM46uHqTUOQPeP3WE9e-YxvjRBjWQzorWBYU0nfMviUO5MBbq4x2SyD08RabZy4MVIh3tPdOh-cI_v71TbaJcRgqX7bkTDY_VDZASt4Hg3xhDtaIYtT_e4PcHHZ4mY-JO-VK-sD4xBD7zfjlTKHsE-WORYrztpt0CzMIV_WUfKXx5s2w__YWmzJ2mkLXQxKJBtu9Vyjwm5bXVqyCJymvbfLsN8erNG9WCU0hhd1LJX0IroSvZbhGWj0ALI3bK_RIdNLUY8gyZ5b1oFA031ecrYAvSNx5WFLD7_kwPQQuA_MUhbnwSGDW4wpidOJMlH7O7s-lEun6VkNgziE7JF8zIs4k1GxjPVXddMJ4vGG9Q6l-_AP57oPFYHfyNQTlq1_l8paIAfBmUOok9BVF10riQj8ggbp4syhDVY7oWk2LVN7mQ6vwWxrcu6waSX3cS4Mr43MkCths6DnDdFq1tWo=w1860-h1060-no">

## 具体描述
视频6s处字幕「而且我们可以绘制直线 很好地拟合这些数据」，应改为「而且我们可以绘制一条很好地拟合这些数据的直线」

**Comment by ChengGoooo** [comment]
Fixed at https://github.com/udacity/subtitles/commit/bd1e6d48927d70826d355579427e303ee0c094fe
