### ISSUE TITLE
3. 自然语言交流> 3.语音识别 > 12. 语音数据 Lab 简介

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#120]
## 课程导航+地址
自然语言交流> 3.语音识别 > [12. 语音数据 Lab 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/7080c29d-1e60-4fe9-81a7-a5657c378ebd#)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267427-57825900-d58f-11e8-92de-ef0a0f381f8f.png)

## 具体描述
49s “有个ASR训练与测试的基准数据库很是流行”可以翻译成“这里有个很常用的ASR训练与测试的基准数据库”

**Comment by yifangwang08** [comment]
感谢您的反馈！
