### ISSUE TITLE
3. 自然语言交流> 3.语音识别 > 21. 深度神经网络语音模型

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#121]
## 课程导航+地址
自然语言交流> 3.语音识别 >  [21. 深度神经网络语音模型](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/a198e171-9f44-46cd-8cd5-ac11e20ea503#)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267452-b9db5980-d58f-11e8-9c66-5757b141e3c4.png)

## 具体描述
2.13s “所以我们可以吧网络的声学部分”这里的“网络”指代不明。我认为可能是指的“上图”

**Comment by yifangwang08** [comment]
感谢您的反馈！
