### ISSUE TITLE
3. 自然语言交流> 3.语音识别 > 22. Connectionist Temporal Classification (CTC)

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#122]
## 课程导航+地址
自然语言交流> 3.语音识别 > [22.Connectionist Temporal Classification (CTC)](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/6a4b1e65-7aee-4016-be36-5a8397c33883)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267480-2191a480-d590-11e8-90cf-0a0ac7c2772f.png)

## 具体描述
* “分布聚集在每个隐藏状态以定义模型”，表述不清。“HMM的发射概率”也不能理解
* 标题没翻译

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，麻烦你看下这里面提到的翻译表述不清是否有更好的翻译
