### ISSUE TITLE
3. 自然语言交流> 3.语音识别 > 24. 参考资料：深度神经网络 ASR

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#123]
## 课程导航+地址
自然语言交流> 3.语音识别 > [24. 参考资料：深度神经网络 ASR](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/3c20697b-fd12-4ac8-afe3-fc8f80b932d4/concepts/ae0f3b43-5800-42d5-8518-9b924c1bc89c)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267510-88af5900-d590-11e8-8b6e-ab0c78844a2e.png)

## 具体描述
链接的论文找不到 

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267514-9cf35600-d590-11e8-8e77-b86e9b99bedd.png)

## 具体描述
Tensorflow的链接也是无效的，可能是因为最近升级了

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该部分内容进行了更新
