### ISSUE TITLE
3. 自然语言交流> 3.语音识别 > 1. 概述

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#125]
## 课程导航+地址
3. 自然语言交流> 3.语音识别 >  [1. 概述](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/171b8584-8533-44b6-99dd-457045654800/concepts/61c0743f-22f1-47db-a4d2-5616c25fc888)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267574-6964fb80-d591-11e8-99a2-be40769a9061.png)

## 具体描述
“先进模型”翻译成“高级模型”会好一点

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
