### ISSUE TITLE
3. 自然语言交流> 3.语音识别 > 3. Workspace：最佳做法

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#127]
## 课程导航+地址
3. 自然语言交流> 3.语音识别 >[3. Workspace：最佳做法](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/171b8584-8533-44b6-99dd-457045654800/concepts/c9eb89f9-e2d9-4969-898a-c738a7721e88)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267604-00ca4e80-d592-11e8-9645-cb374320a48d.png)

## 具体描述
格式错误

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267611-1475b500-d592-11e8-8a22-8f6cd05314db.png)

## 具体描述
这里的意思是说，workspace不能自动保存吗？如果是的最好强调一下

## 截图
![default](https://user-images.githubusercontent.com/13103405/47267613-1d668680-d592-11e8-87f9-5b90419f2497.png)

## 具体描述
格式错误

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
