### ISSUE TITLE
3. 自然语言交流> 3.语音识别 >5. VUI 语音识别器 Workspace

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#128]
## 课程导航+地址
3. 自然语言交流> 3.语音识别 > [5. VUI 语音识别器 Workspace](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/171b8584-8533-44b6-99dd-457045654800/concepts/f4f4ac78-d88a-40cf-80c1-60d9f8b742b3)

## 具体描述
项目文件没有翻译

**Comment by UdacityShuwenLiu** [comment]
已修复
