### ISSUE TITLE
自然语言运算 > 情感分析 > 3. Notebook：利用常规分类器进行情感分析 - notebook錯誤

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#129]
## 课程导航+地址
自然语言运算 > 情感分析 > [3. Notebook：利用常规分类器进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/648d1e34-9ddc-45d7-8e25-c51aeef92640#)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/emFim-pKg9TZYvgWSR_Zw0v7xthAvG1dY5ETZwFysBYmVwEKlYoI-j9SGE2G8XWyeYCGQ-Aq5yj9rUk39BtMPVOAzEzZBRzaC1Lk6Mx-cVDFyDJyY4wlCTXbWjeu2HNghWVP_kl4hCditZlLHDBUrLN7YCtKJDpPzWs10okZD8Pcv7sBScAvcyETVfbMTaaCc-_JrK8-snSqa6j4hK26_B8J-zrZ_zbx8xQ8ehSBacV2H5aEB2YVyI5SYKjqT-PgTclh7aj3x077CbTDlVegTlXed4CS1ylcJq6OdX7DuZT1ty7PCn-7Q8t5AbI_1PDsavoYbKnpXlOONTCUoIgkHxyCLIDm1DTPR7kgq8d9k-6I343pXzK9hJCyBDzzpeaJ0R900TIwJDIDhL_16fQtknV7Mfd5QD9T45xyfSKs3ApAIB_iEIh9p6W2gb2wzB1zwTP1gFsogWLB5gB5-xpJXMOgsaEXZokdTQ7aGna9PkRekFtM5ErXbUexVswrRAW-kleV_lKCFNMgCyBfBDoueutBfIbyG6If_q8BN4cPDDsFPj0l9GUbJIoSDMcyvCqGY2NmrowTHjO56GNODNMdsLibouAuUiXoleBvzYJviDJwCn4gCenT2rasvUamTCM=w2360-h1250-no">

## 具体描述
目前notebook为英文版，并未设为中文版, sentiment_analysis-zh.ipynb

**Comment by sylviasun916** [comment]
有汉化的中文版文件哦，名为 sentiment_analysis-zh.ipynb

**Comment by UdacityShuwenLiu** [comment]
已修复
