### ISSUE TITLE
1.自然语言处理入门 > 课程3.自然语言处理简介 > [1. Arpan 简介]：字幕翻译建议

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#13]
## 课程导航+地址
自然语言处理入门 > 课程3.自然语言处理简介 > [1. Arpan 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/e79dd351-a1d3-426d-a259-bf8cf9a26a98/concepts/100652de-12a9-448d-812d-e0fdba72c6fc)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46902326-23a39580-cef6-11e8-8ae0-8f09680d031c.png)

![image](https://user-images.githubusercontent.com/3198940/46902359-b0e6ea00-cef6-11e8-91b0-ac5b96597258.png)

## 具体描述
视频15s处字幕“原始文本”，需改为“传统的纯文本”

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46902487-da087a00-cef8-11e8-8454-2748a7922c53.png)

## 具体描述
视频 28s 字幕“简化”，建议改为“转换”。
词性一般都用转换。
建议翻译：
“将动词词语转换为它们的词根形式，等等”

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46902632-0a511800-cefb-11e8-81a1-96f2f4977d04.png)

## 具体描述
这里场景下，推荐翻译“你怎样处理你的纯文本内容”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
