### ISSUE TITLE
自然语言运算 > 情感分析 > 4. [解决方案]：利用常规分类器进行情感分析 - notebook錯誤

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#130]
## 课程导航+地址
自然语言运算 > 情感分析 > [4. [解决方案]：利用常规分类器进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/6f3626f0-0917-4efc-ab52-74d26269b929#)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/MpYBiuY7BhQ_Ha2S66nUTYCObvCBAP8h3MtKzaKoO5nxI3RvNArt47R0W-SeR0nuVpXzBmXBZyGIzFajNOfoVTHqUcJHUShfesn3cClYw76X0brjtnovDlbpvAsxuOCc-YXF0OCy_iNZNNCMydFS0FpLaxQ7KUy6td7pdf9-yfIFyoq6XTYlC-ICGgn8bARwan3F1ey8h80u1DonH6CtxFOsWsM1gqJ6VRyntcX9wo3uaMnBvL4bPqbGreQpyqcxekyr2T9lPem6O9v5jTqZYmuWKSePU1NqHl09j2LgQGxc7XI2a81eOIx5IGo6J8x3ckkMC3xomgFDwsr0CBnkbVvH-infS0j1sutHThxR8yVFD7T2DWRfFOnhWSLPstS4YndlT-VKfBo15KL3ThHIK-mGz1dsyBbcB9iOFtI3cLlOePqxywoivGm5b6flA4pgZMdODubpvR8Z2B_fTAuCv3E603Gw10DLr6qQABsVeMBgDG_xwXcMYyRPnHyQqBHuc7mV5tWwWHHEgtWQ-gNn9NZAU1gu2oz0QKiXlpSiNPwzLs6a_7vmsXhaj7F_ZoQiLmL0IvShgugjiSrIUeSoDThd3YSMxcfRIC_CHtE7kvYJb-NMQncmhViEB6p9x64=w2378-h1214-no">

## 具体描述
目前notebook为英文版，并未设为中文版, sentiment_analysis_solution-zh.ipynb

**Comment by UdacityShuwenLiu** [comment]
已解决
