### ISSUE TITLE
自然语言运算 > 情感分析 > 5. 利用 RNN 进行情感分析 - 链接错误

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#131]
## 课程导航+地址
自然语言运算 > 情感分析 > [5. 利用 RNN 进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/5d87edd4-2f79-4fd8-9e34-f21118ec7b29)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/PFqQ7qZnOso30tm-9jGE6ok8kUEDzru3WzqaWtWIUbfh_zosEbp1KiWR2n_nUU0dcFR-fWOBi79yS4qzO4d7m6n57b7t-NU_fuzRQ9rcAKYplamCJ5ffHshN90EQipjW6OybGQhcejnxUac3cq3SysrBZKjhtUzlzLxejBrtYj8LogF63PW1TfFSQEFD8COkw5Rm5z_JCMJGSejI4phV7gK0UbwbWKJZprBPZkzGALA1nqXbsTJpQy4hdyyps6uTx9zrHebLe7dIGiDSelMuoVRhXXfPxb0o9CslvxVSEjlbp_rsIkveqhAjfjGxX0cmIuttnFZHuJl39LFVUEVOm3WbfiScNpNcRb04bdhh_ih3qBlahdwxJW8BKqEqVUjdkgawWS7r6xj5iAgZfgfEieg8OPbke7Q7gbtCvHmz-ARNnMZx9i2w9N0kIl-BvVNBV8PT7mRpYXKhe0ftLKVCpOJ3K3N8Gr-edArwr42RVv-waeDXS8CXVq7MI3rNRGuyAaTo9ulGTBFvtUx2xc4XsmHxWdscyfz1gb9f3LRJVRPvO1qM1pO3ZJzT6E5MuCTVAzXk9u-uofNENEFnHwho2cLaYQ6fwiUIkLltTdj5X5w3TJ_FncwjZXtI5plr8gQ=w1422-h398-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Wh7hVUvLueITwRl_2KgTj0ge4sjMQL1YB5f6TGSGPSSHEVcxNBYGS0koMA9YVajXSai3sLJq_uYE3Lmz-Ehy4l3hdQCioWlbykP_Si1Qo0lGkx0z6DZpeiS_sRnH9k67jFELTbvKETuM09_KLr2d5oZZexG4JfpiLWfq3diGMmqXnIDYECdA46AbGcfa7BcU_CrECU7uyAJ-lYA5RPR4L6GgCsiH7FbVQyGsf8p3ZsfTVkgN8U_aO6jviYVoM9nvJfY4rte7o0QXZpmjIFU2YKYAFrKwh21_sFy1hc6wLQ-Gul5nylWR1NWfVhPWmx3wIUz6Trozkh3w6zvxQe32HgOrT-JRqZ0wOw7rkq1sc1RZxq7K1dqEWuapGKY19HfLZXwB7okiIix0Ocmsv1uSStuU_nlJP0JYz5ZrNXWvCIb_PEQe-xMvS8fO90T8qejomKuohLqgR5z2MwqMV5-6sUJjBOQVdXn_y-XsifhhwUYDnKlbDJ2nPzu25i8XvVWEkHnZeht9hR5lRUJdn8yocYEYGO2NzUH1LM0456B7k7PImg8uEBt5fSkwSDL0l9-Cxt5yHuLaYJrSyYyQqK3v1kJTMEvN3KPwsljAHrcBOwPpW3OgUgU2McgXp5TO5H4=w2508-h1262-no">

## 具体描述
文中的「递归神经网络」和「Keras 链接」并不能正常打开

**Comment by ChengGoooo** [comment]
## 课程结构
这一部分内容结构似乎有问题。看起来不应该再在中文版选修里放一边。等腿哥确认。

## issue 里报告的问题
链接指向了美国区课程，预计在中文版删除链接换用文字描述。英文版无法改动。

**Comment by ChengGoooo** [comment]
链接替换成文字描述，避免引用的时候链接指向不对。

删除选修部分的重复内容。
