### ISSUE TITLE
自然语言运算 > 情感分析 > 6. Notebook：利用 RNN 进行情感分析 - notebook錯誤

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#132]
## 课程导航+地址
自然语言运算 > 情感分析 > [6. Notebook：利用 RNN 进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/712c0605-2d22-48af-b60a-5dbd39895c19#)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/y1CTfkT-a7M82HlezMtn2t1NbJTCVS7ItEjPzDHjeYud3q7GGPWgbI5nTD81FJq5eeavs4WhOe-AOz04KVjDq7JBrFsx5gU5zGIIlADV4DLLE-4i9aZqMSPbJd8iR0ig3Zr6h3fwErt7PHNcNgyDnnQU48KhKGtCLkQsL68FqL2ogNKPRMgxSPePGzibLiJHh35EKbmYmR7EDwlQihUZ0Aeti37VWwJMlTDhzauajiUqBqF_OFYb9jTuCWT5AiG1pV-evXxagkfGiFVZyWfjAWGvsnU860pDjGdDjNQoNiMgfaTt7Ap6tnuOu6roTB1-vrgvKhkiV34xCChih-x0qsSaCmmOksBMq8gNVXYUlI7j-V3vQSPjrTAQ4Uk72lrAtHPPb_IdtIsoX4CLT7iQi57MBYDdcRtpv90fruF0zJPIcUmQehLbMaFQWF564bi2BLQPHqXOBNAlJR-HCtXKN9VsvlROcmlph8d_1u71BOz7Y3SR_zbpr8z4otJwjwqAwSvV45M2VnTKCvCWsuABhViYGOx8mFZS2D2YQKdoyBrNxZ4a41K5bHJc0sSY4Ho7OVPx75l0qLENV-OwoWL6wb2E-TxEyzh8KwJO4YdqP6z192h1FLTSwf-h5mRiFRA=w597-h318-no">

## 具体描述
目前notebook为英文版，并未设为中文版, rnn_sentiment_analysis-zh.ipynb

**Comment by UdacityShuwenLiu** [comment]
已解决
