### ISSUE TITLE
自然语言运算 > 情感分析 > 7. [解决方案]：利用 RNN 进行情感分析 - notebook錯誤

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#133]
## 课程导航+地址
自然语言运算 > 情感分析 > [7. [解决方案]：利用 RNN 进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/dd9a41e8-0557-4d92-ade0-d27259cf8abf)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Av4jfOGLXk8RH1g0O1RVeGrW6ByEGbIMoHn37yJMViLz-1gZRy9Zimt4RkgEfHr4V-_sAk3BplwPpC0soicr8C1jn0oK2n_enXR1N1tUNYiMMfPKTwFT6mbcV9rhEjeO45csDeq41XdnKSQypMDgoXTB9Q_HRNUpbopmr117FaflN43nSqk9HfaOpudagaPgZuORIynF5e91XzpR2QpDBpkl1K0xXcMotyiA2tdTI4edJ9vcE2Dnu9F5_kUhHE-EEkc4A81JMEGkEfd1ZeUHUQQtIO3riGjbfRRYWW8UWPsIq3Fp92cf7qwG8OFRbwOPaXAXMklFGo32Ns8X1wZbH5TdOS0owh8U7HOjt1DeEWbPHMwKpB7JDZAiDjRU3StITsiTXf3GZLDUnyWa897IRMfExw7z4gYvFy2fm7q3A8ATmZsHJuxRcts51ovRBWeOrwiHWXYv4uQH5f7m9ixaWajgJkVEW8_iLTIvIgQSrOSHmvemdMcaqn9QHJGU6GzX5pNV2beyB2aivNfZ67t_DdH1tKPQMt4uFS18HwFt1vtEu43H0-sDcLcoXjUiefSs7iza559-O69QQwbmX8xvWKD3lrDUnNuqkhjlQBu7gyKrUPBFi6Bv4rIXVSScCjo=w2416-h1258-no">

## 具体描述

目前notebook为英文版，并未设为中文版, rnn_sentiment_analysis_solution-zh.ipynb

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Z4a_ViN0EmimgOS3jVoQS5uJE4PLQck4LiSEiXQNpMV-FZNwcF4jorploVA0NRkYDbtGND3Xf6Zd6ZI0QXDyMnrhfDPC189ASmUZPBHiCsKPzzIfXnxvAYpsxY_P8S766_iKGTJjsBMfN16SWkuQFoDI3aj5_pGiVhhviHOH5aJxm72m6Y3btcXNwik1qKjCoFJ3GRBLdnEss0g6tbkXb_lg4FCItyZJsVuvFV4FhNLrhWssV9BnozA9X6yXAiB7l5NC_xPOvnwWgQCz_m48lMk588VrNcdTmtJbAitGf_0kHKYQISTehKuaoTkUdC6hJYqElVEaED4_ku65ZdrNkU9wwquBNDJaZsXVkFZK-ULjKS7RivwasgJ3mcmgAI6EjNgLX0bBmekGKV8b3F8Rzp4uI1C0OvdBvqsVLLwSg5ayGQff2yKbCn5-XOZNi_aUMgezXwuXISaR468WQ0WwS3puD9VfiEVxQQ0QKR2WW3EPOm9naifA3vMM4qQ3EIFZjr3j-G3qRGDPCgyCLnxghVMA57v_I3izhb4LbODjss3gDSefRL7J-5cQIXbIz8rMUHHOhHP2Fsgi_xo4ljDO3qrhnUlBG8P22pw2qPeJnThbcQ0llH8lSCnfEh4zj68=w2264-h324-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/kATbjHTnP1YV_Hiw-j-s6vu7kne6zf4Lc6Wphn6Zmhg38TboLY8fehDAXWyanxucHPsi3dMLi3O0QEfQtmM5dsebYABJLuPQTnlbJEnrmEu-XMuGEZI_1TZ3KGwlhXVQT_OjqcXUePvkjbbSobYD6FONnd2kLkp9zeEx2XO_TckoEFLa6Py-xliDQ857ict5i1ouHyKkzflCIYxwgGEgFIZ615qJmjwsVOeKdFOU5d82T28p2kBKcIv7ug6ePMWyLBxZErs22e79Y66MObOQKDSSbxwvQL0z1lCF-PXAumuRGQtduDaNNGbyMMfuF-iQR27FDJNcxWjbixz3-vXdlCU60_E7gckT1cuvqbIYwXbmBccUyExdCgOP4HPxCp-7tDdXCK1SOOfH-6XgDANmTh1icFNQNBlWn0aTT9LvsY1dO9ga6BEXgjPG4hCTRmAi16uPICu1tGW_eG3YW6BbAyWHqm3zZnNfrHQOXRVwYfjshKsoUf8-w72xg1PDgudKgB1jiXyavEbI-OWq5O2Ppmgdx_G4YEpCPBjLWf8mJUyMaSVfGKO8Ho-0RaDUDreblIVB5CGItNAJhRD6ma_MmRj02_NYC4ocWKPxipQErR_yK7zlf16EAU9SF_acXzc=w2298-h672-no">

## 具体描述
notebook中的格式有跑版，原本的输出栏位变成了编程栏位。

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，关于 notebook 是英文版的问题，跟淑雯沟通后她说可能是翻译没上传的问题

**Comment by sylviasun916** [comment]
@UdacityShuwenLiu  Hi Shuwen 我们后台查一下，是都有翻译过的版本的哈。 
![image](https://user-images.githubusercontent.com/31837843/47337856-53a62200-d6c8-11e8-80d0-caf2aa5ec3f0.png)


麻烦看一下哦，谢谢！ 内测学员提及的 notebook 格式问题，也麻烦看一下哦，谢谢。

**Comment by UdacityShuwenLiu** [comment]
已解决
