### ISSUE TITLE
自然语言运算 > 序列到序列 > 3. 介绍 Jay - 专有名词不一致

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#136]
## 课程导航+地址
自然语言运算 > 序列到序列 > [3. 介绍 Jay](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/e926d323-9f84-4b2c-bbeb-0fa8e56c0c43/concepts/ab43e169-e8fb-49c4-b7ca-b677cfa29445)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/AN9UTMvuQHsIRrNrbKfi420yWB7AaIgujPcBS4CbSjiv1TZaMxelqXSSI0AL0AVTPWw4C4gFbKMhWFUb0ONlLmpQRB23_iIJ5lloeNLJlZSV8aem3Cn94EtavcB8QBU4w2OcN79C9Dywy0fqwSF02O6LHgdMN5E5qGrLKQIhkqpcIJYw5D0_HX0kJpgw8GEabvKNDdschBthq7IaCkjd6UGenNk86fJYUO4rQeyctQCVZenw4c7r4Q2pFLRPkUbA-cgca9Jy2fA2R_qL2AETkB62GFr_3RGZRQocbL4zYyhiMVQEVidmFnkBW5cXfYHurm2Z0p7tiXpOSefvxCxZvWgiBmiaiC_ncWlYufbHUeR3fhOoG6FCjXTfetUUR1O1PBRCJguU26Za5rrC24D2p2UQQUG22d-1XgH02Kk5ilxbGDtlOTQ24d4Xj4t1av-uUh4aJQKZLG9UB6aZdeDclfZMvAm7KbEJCWGt3YaWCuo8zPFSjE-5cP1Mf_tAeB_96Pwg8b-pFBBXjPamjil8aXNTPKCe2mSY6drArkzPRxQK9AjblIF3dHSspAGZxNE9V9BFK_VtwvxO15WtjwlwVit1a55CQ2m8tHrMmd3DiL5-O5u2b7nFe9V4qTk3UOU=w459-h296-no">

## 具体描述
视频1m29s处字幕「递归神经网络(RNN)」，需改为「循环神经网络」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
