### ISSUE TITLE
自然语言运算 > 序列到序列 > 5. 架构 - 专有名词不一致

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#137]
## 课程导航+地址
自然语言运算 > 序列到序列 > [5. 架构](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/e926d323-9f84-4b2c-bbeb-0fa8e56c0c43/concepts/be468484-4bd5-4fb0-82d6-5f5697af07da)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/ZNbSjP3_2HN00C17WFqo7mXkNGHpctZ1Su3IqGP2wX5aS6ydVqe_HcHM1x9a36E1Vh9hjlLsaXPx6Ghyyiy__AG-dQgNrsjNbnk_qMiM3TwI9SG6otay0RiRNtHMi40Jru3psOn-u9l-wEzdoRXdhhPk90ftrxX76DJt2qAwWPtljILy1AxUQLPAxnPdaHzrFBGOYVNmpdZ81opjPoN6y-_StZcCK436JX6z4E3DLDO8Bv_iZ0gdKks-VP-twNWFwIUyD6sA9wPFDrGbvB-KO_9O_4HU8IvbYc1U92igaL_Ig0A_rSAGlD0rP1sm7n1_MMzDUb37NB3P9pyhidDM6Sb52I7oL45jXq5U4Q8UPXawQ-zDKtkwPnC6JFLaJK9Jhs5dE0zZzow05V7TFKdp-_Oi2tAmKdrnwPfuxVH160_YjbhhRQd-T7YNgY8D5zubV9RLELP0IPstJfzXk9F5lPtr1lUlcTu7K8UWJ76o6owgAQX_fvFWqdoXGHKCn0Aq_rrrPo2RzilNjzuYzxY2i5hSlEZ9y-zVeG3e2O3EdOxUUE50v3Wzvrn5pdiZjvK1GWh6M20zBrsF7JfnES-yayAyHgKFuhpPUPGNo39i037Z7p5kJUPEpIVjmOdE_UA=w437-h296-no">

## 具体描述
视频12s处字幕「这是两个递归网络」，需改为这是「两个循环神经网络 」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
