### ISSUE TITLE
自然语言运算 > 深度學習注意力機制 > 2. 序列到序列小结 - 专有名词不一致

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#138]
## 课程导航+地址
自然语言运算 > 深度學習注意力機制 > [2. 序列到序列小结](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/876fd2a9-a1c0-4255-bbed-615c9459d295)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/5fHoF-Dr333fXB1zKiD0B4SgwTNzloW_YjMJfQvr5KSWUhfzznW6-F4CWUZkEn_q2d_G4wKXq48tuK5hQJYZ0qH3nmIXLiQx4hwLNFz5xG489ZP3XCMbipZOY-smx6zkWxlFIP5OHGSRml6aP089kJly0aoYtT865dQfOAo2WmESJE7nlWS2xJw2oI8OB-7A7KatWuGz0ZZhbejERKyAvbHimnKq60GKFBfRRKW2A9bVXcX82Ai4p-dh3aWm4H1tqf9SHEKtI_26-yHciJnQd-S5gnIjBgAGin-CqlzxnWdLHsGR-_6cam26iwDYuKFk1WE2lq_tICRZvd8KiINv_gTmMULcogL4VVfFLpyhpkiwW0mU2haL4TWJYbsY4lzadxvPTkUEMDncylBYGwM4kC5EcrK8Bz34oR2g7CQZ17NzWWtiwvSWA3yp-RFskzlzCRsioDFDwZkJorkL2YQ77UryAltAoYWdM-cmgb8RhLHqLKb3mWv6VE6UUFSC4-pS72YJZCDCgcNRc1IAcV335H77-kIFgLk88jvo850rfxXLEN-t4gEd_TQlitH7xCLIq7kl8K-TL1f7eXN6NKyF_173daJ6dPZYmOBOU_Xx3xJpRjNn5CUnG9T8yrxiuf_-vgLjh6Rd1wKn3te8xTvHU-S1=w1748-h1170-no">

## 具体描述
视频1m9s处字幕「编码器和解码器都是递归神经网络」，需改为「编码器和解码器都是循环神经网络」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
