### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 16. Transformer 和自注意力 - 投影片错误

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#139]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [16. Transformer 和自注意力](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/48b7d2a3-2b9c-46fa-8491-ac070688a758)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/GY-FrrXUGKUM4bfpd9ZfUomwF2PvuP82Wa7C-XCOUGO-6AsUaQV8PoEceC3bBve0KDaOtV5DSVxnhWEbuZqz4NIHwBH8P_7hLp3QRM0DpkJMXTOZU4pcVL68DdFZRA21UrFkXjwCAIjp_3MBnJio6PHVVg5UDsr5qBaD93RXCszd52iagPp8QmghDSbe66zj-itpR0OAlezvzhC89Uwiejm1Lzw084VyW7_-9u7cBtKpoGs5mT0SB1Ii5xiiytA9cyo3YydYZStkXcIozaZ1JjmbNv2kCt-GaII5htUgdAtO8dqZUMKeNOpHGvD2VeS1exIwKsWtwFNryZoMTbVzPf6vEWG9hzaWVx8Dlj0wITEZ_0h0ia2gIlzcj0TXClse7CVbmwQwNYZUzbbIDfQqkrFRoseXJXaxWEm1SI7HGNQZBReuWp3u0-hIXSd3_kjQ5bwQBVLbMfmXykNIvNe9z1GprV2oSvkjnDNVhH4k40K0lnZ3eTKdJ17x-55cD_RisEsQUdobmiUw7ejRQRgGNzS_JCRbCwwT715FOsgSS3HwFi8F2dr5YmXTi2ocLfdfH7i2n2ERX8f5S9hVYZzMtMIvzV4VYrtNHaQ7EdCV6z4SN_H6KgoD7i1yGeeMd5hC6OpvkV_3g9IYWgza9altEei-=w1676-h1192-no">

## 具体描述
根据视频前半段的说明，视频2m27s处投影片中的40应修正成28，0.27和0.73位置应该对调

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，麻烦你看下这个视频中的内容是否有误，有错误的话可以在视频下方备注说明一下，没错的话可以跟学员解释一下~

**Comment by UdacityShuwenLiu** [comment]
感谢反馈，已增加注释
