### ISSUE TITLE
自然语言运算 > 回归 > 4. 用数据拟合直线 - 翻译问题

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#14]
## 课程导航+地址
自然语言运算 > 回归 > [4. 用数据拟合直线](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/e5d39837-1c4d-49c2-9884-97edcec7fb4a)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/15JusplyuYYQBR4pViF92ElB4JlS7OmmJA3KM2UeBx5tCuxln5iS_xisLD1q4-R1lyS8iUqri4oyginmz6W55jJVkeEDSTPcEu74kdLemSVq7ZYEHbbhklrcL7ZrqvvbuNLXBNKh8dQTWZKJ1t4OLWRx1culx_dksCYWbwUNcS_ueSuui4mQ4RMI4uOSgAeul5e63zvbi2Tdl06CstpgVY28S0tj2ND6WpkQrGFCriks2ZtN1Gn423t06Tf_Zo1KPGz27BlPp43Lrv-CA-Cj7GejqDnt8egRFZZcX1tGmWZy1md7baC0Gep-FDyohfn_ypsHjJuKkxoGRasfZ5VLWYkO-5e9eQHmFRJqe1HYrJY-9-qtZj9CnT6OceFq_5rhJqKOKwuokvG0aKGXOD96_M_QT2d8xX6X2T0HxVlSEdAbBMkS1r7xUrmy1_edZMHEznC1M0iiu29TdsZeI9-l45bW6fI32yyS40kqkEAUvaigAzvFdZ7HDzQY9fGoJHyemCZwx7STcUJy-wMP9XUefHOs6Pq_DJM_3NYxivE5vdpDf2EdUXJV_asLDYUiKv2B9kf2HLo1X-05QfcmNFuSbOyIUWHJ9nGiqq3WDLYHKShyA09tu7UIEQC6SeEDhFk=w1886-h1078-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/0boTDgr2q4givxwp0d8d3IU5l4BYqeOxrbp9T7ZJbXggYJhpmhT-0V6qPVe5SUTUR-OAbHCkmlmRp-ZfZQNgQLLWWacASWZ_WPweYTqcCcVVr39S0DhEAYo4JLf9P7cHqwu0pP30ALfKqjVnIcTvZhAtqjJCLKZovj6chGRsVVZ1mJC97CspzkFtYXsv6_6Ziuhml0wF5qM1QVwad--C1eW6964xoU-skFDRORUHiAzLH9Boy-IU0peVTCFSRdapCMLPZYrLwsukFjYZn7D6AeEpHDW06U5BMZttHqgfS4mkmzom7CBe_l_xiHBIilr7H5i5DFE3QKB__Kti7-tb7zIw7NtsvEWHWG9LQgKsEsOARgJODcNTOlTy7Z_x89LwQyaLI26siRZtZvTd9foCPzqyzGqp9xsVXCoKE5k4pqvBLsfiu_o5B_-lGjIsC9W1Nlttafnpq5rvKyLGqMXwohRDXkhiMCKxWd0bYoFt_W1lu9tSptbjgxkQwLmCSWmfSualHOrcL-1LWebeoCT3nhGrkrD5TaM-RiN_tl_3gBl1SHIQy1rKVwtzfmHLnEyiv8PY80r-WqDBuu1nxtHHTWhVmklmEz3lZOaJDtIdCfokt-muLpkMirWdI85FJg8=w1860-h1076-no">

## 具体描述
视频1s处字幕 「所以这是个计策 用点来帮助我们拟合直线是有技巧的」，需改为「所以接下来要讨论一个技巧 如何使用这些点来帮助我们找到这条拟合直线」

视频5s处字幕 「我们可以说这有些点 可以先从绘制随机直线开始」，需改为「假设这有些点 我们先从绘制随机直线开始」

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个视频的字幕在字幕包里没找到。麻烦你看下哈

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
