### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 16. Transformer 和自注意力 - 链接遗失

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#140]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [16. Transformer 和自注意力](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/48b7d2a3-2b9c-46fa-8491-ac070688a758)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/7vZ7GZcQ6OFfBVPEE2JpzBze8cAxzp-YEltlvQyu5gL1GD6QZWgN5QE297eyTH_mKirrDifjYkOQOWmdLkhcA3qdepQYl1nEDMcZihSl64RZTlQMltgUuJN2oSRHg2jPvT6lf62zRVyR9rpLuRFuqc8FMeGh-oBK3PspY3tiGi0hn81SKywxASvnGBOwSVtczArxB2eMcKrsX9FwOa432RQQlQpAjSAlP8e-c9hGd9C9SlYEOtYaPCUkbgo65wXDzd5V9yT5fm4l6HBzvzkJEDFqfXIAF0_OpY_vgwWUX-097uYv4U6RqLn4FJjzDfhY8LaclUHIYYbwQy7U9TDW0ziw6eGDbMN5qqfxSvJrhLjdzndaBYho9uOFUgemTFXwT8jqbxPyb44p6Ed2pmLyp4WMFsU2e2xBT2v8PioR6vOC8xPqQo-bLOY0ET8zx0XajRzCuDL2En0bnnblnB3d1ri_Y0pD1pKt9cmB11rtEv6XagsLn7rYXxP81dUnSTsDuE4OnU-GAkzYLQ1RXIQ8kNiVv5SUURtXHp9w31mFy92og0Ixtfw1BPQZYernHO7ZJLyrIIfnW0Pzfi4XSyFiHl0gxj_uSZBHFwSac0zpsK_IDcQ2AzMMnU6_fiRho6Z30u1FvjJHW2qfLjJre2HRZRO5=w1606-h1154-no">

## 具体描述
视频4m17s处提及下方有放置论文和实现的链接，但视频并无相关链接

**Comment by yifangwang08** [comment]
感谢反馈！
