### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 17. Notebook：注意力基础知识 - notebook錯誤

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#141]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [17. Notebook：注意力基础知识](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/f3030c2f-2662-4d89-8938-578c7473066f)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/TSR8hbTILoo2t0Y3cp8m1Z2Ru07Cpin23hoPjf7NEtqf4ArrZEQmwOY-2juUsXP8uO-ZdA0mAUo44qtC3n_Gjjha3Wzm2aMFXj3zMw0ifPQu8OW54_FCCw7PFBboyi-jV5sGoVHo6_FbeRi_EyFtHbsGYZwj9ptZxJhB6AmpWzJjydjQerWhL5mCvavONko_0l9-33Av7tuJQdPDauJZ9A7BCTi-9_WsgLM-G2Osjr_mnC-5ooZE922W4aqoOQZL8Un_KgHn1B1Wg6uljRL-WGQM1lDET_sKCWDfjXA5Qq1XDdgRna5RPw45AGIpTch43bLv9XURxkBKl4cVRCnl-5TlmhxUkIEDoWO9k5w9vX8YxSY55THte3i2we7Yx6XnFTsk7svoFgvQKJ50-wx6YzTiFDLoPJc3mxKe3OYZkHfknwgZxGa8Xi-MFCLQC87O9MmEVx3-L8CQDF39-K2P651IMXK6_J33FY8FkrAABkm-ysT5m_i3wP1-1UbSQQ7C4jGX1iktYT3lrRWhzuEA8jS_jCeUEcKeLP0D2eJVrhyssfNSlqt1Z_ftupGdqouC_bKYS8d3OkW_LH5fFpnpxQVuwlqqEELTGG4iEa2IigF4LrCkIJtka6qU--unpKA8sny5-n5NHXe84htTIbPHFXAF=w2270-h1164-no">

## 具体描述
目前notebook为英文版，并未设为中文版, Attention Basics-zh.ipynb

**Comment by yifangwang08** [comment]
感谢反馈
