### ISSUE TITLE
自然语言运算 > RNN Keras Lab > 2. 机器翻译 - 专有名词不一致

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#143]
## 课程导航+地址
自然语言运算 > RNN Keras Lab > [2. 机器翻译](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/06c89f82-2fd1-409e-9d09-e785d32036d7/concepts/3ea3dcb6-7ee0-45c0-955d-5bec5c9f3a25)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/pbxARHIesiFiH-jW6lS89eshRWA_tzMvSL17VQNYYgbX8qP715BTrLyi3yYreCXlOqz69ADJmvspjMSeVyk22QUqJzMuEmwE8i1czkxHN3uOyGulVta-FrEh7dxr8HuLlKQDPc7JB0tnBJ_jaG3va-lzKWzPYzFkxAWJNruLRx4YR9bo-I2uzFmgBBhK1UVbSlbhpNc3wxZLz-0V1XeQM3QcjyR-J1IjKfI3MsNK_ybVD8-GVBy0sYSwCGh_4c9-e4M6bei5mkKJaAjqdipJ6Jt6qK3rd_Z8q3nWQe20GMxDOixB0TntSj3y470uPEvRMw3mcJy-dDSFcCLN9-aihewDJmQZOTdXc5RDSpft1oBAeDSetGjJ-AYj33d7OecPdGrQFLFlnPRQ7VnxHXEcPMwZ5Bq2QD2U5WWXYu15V4_isC6MDLDvbgzwbQRIU6Y6O_OKKsIZiLltEuCTfRy_5z8NF_L9eBWfHHAdcJfB2dhIKYc52UDegzwbFoZHfvfxkOCAvYGuCh8eJuaIKOPTTLeWo9Ei6mRz_1SFu3vqMmRy-3CPtGx29VAep5_DW7-9jQLJy1jr20P2nhpRm50_46V3ZrEF7jZV4PpQ9jnv5ZFC-Hh0y5ju1270QA5FMISySEKPtckQEUsQv_DExC-jXGx9=w1318-h438-no">

## 具体描述
内文中有使用「递归神经网络」或者「递归层」，建议修正为「循环神经网络」或者「循环层」

**Comment by ChengGoooo** [comment]
已修改，感谢反馈。
