### ISSUE TITLE
自然语言运算 > RNN Keras Lab > 4. [解决方案]解密字符级 RNN 的代码 - notebook錯誤

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#145]
## 课程导航+地址
自然语言运算 > RNN Keras Lab > 4. [[解决方案]解密字符级 RNN 的代码](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/06c89f82-2fd1-409e-9d09-e785d32036d7/concepts/46fd995b-27ce-4553-b9c4-8bca3d0ffa3a)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/mPqKhMgZ-ySL68R4unBNsOcyDCg4AxdrJp4zXVdujsCo1APi2I00YbF8BfCv5XL9xRYZ752fegNRWCbiY-mrUJy6YKMSged89fVakUxmkqxO0hHTiZ7g03Ho_JJQ1HGbX4WiJG0F240cIoNg-pT9lWdtq5LwpFFWK-xt88VCGIZWEh7WUc5w3c238ntDch37d4pJcmoUV7HzMW2Jusr01Dg5bB7dMzchTcEdiBvfCBpQYrLEDQBZGjfYIA_C2o8B2qdznuTpm9uz4oi2LSFnQcPlut_UN55IG7dyMgraPLVNbo-b5h4llHdXPgWc4y4g7xXfFLgrh0uOexKu0LgU-uw_ucFx1waWl_3kipS44srhZGddhBQMgwzC1rz6ZziwSnqNOr5SFJ7u6IJL1-JN8TQpt3bsOxoy8Xm5LPEQBl33ikzxrP_G_62TFo1vVaxsNAAShJvsNPcf41i9Negixtu2iAF6APTR8PfsQtGw9rveKioNfwMxeLJWr1C1zjYnCLtCXFGFvZchAkc1F-xQcNm-_sVhuusZD-11CxTAMUb_yRYd_Podujjo1Y0iMiTQb7FWRgymNcm6eQwrZ3_yiU0EvrVqXRj_HDh1XQgDfQFzpxZk7YuEll5myJQSzDz_9wU9Kau1tSCaptwOP6nS2ktG=w2340-h1154-no">

## 具体描述
目前notebook为英文版，并未设为中文版, SOLUTION Deciphering Code with Character-Level RNN-zh

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/-dXLYMoh6x5cHnzNfMtqAL8ABgbLfUfwNjPUVkdzpxXOeFhwGveJLRZ0HGBaKbxe9uLSdqBsYVGsM_bnALAFPcLKhTntSQeo_ISs5awloe-YUR-Bn5PKWrZ-cc0aLMmpviU7FUCOdr5vQIxeZ0Qt0GWANJTtmf9JMFxQdgp3seOgNRs39s6fmgO1rPrNLKtbm0Vy1c8g3oYUWMSkPV256yC7iiXX6-5jxLS8vF-Ow5QU1ibDo7ayyu36uBAzNZrtBhd54A4uvTDassiI9g4jg8jsy5xhjO5NjPTDx7p2zHvx1nW0HVZNI2y5bFflcIJj2kzdceMx5sQNEwBiMjdRU_6jPJhNNEqbaP-qLVr-EuyBL93QEr-xpXbUkdiQmNn4OWhyPcGqEfXZJyMvWbdP6XkrOBHZhFMASvO8Gyq5s3oLjFdSdN0r46yibeYxAQ4Z0NU7vBZ-hEzdmdkT2Edn4WVSW6ofooVHHvlcw9srRuGKT16_7tmYNLymzxujSy4o1wFaFtIF4yMbcKWZJFYttJm28nd3GTj83QYegpIukhoqpwVSc7erhz9QFQ5i1A7Sa1YMnzlCH2zQj_US0OpfrPBUlGbitgPdf3P0ttPL4cOf-E10eqsMC4i_kHW_chi_MdCfGvEF0ou2GKvdb2cSoXA6=w706-h258-no">

## 具体描述
notebook中的格式有跑版，原本的输出栏位变成了编程栏位。

**Comment by UdacityShuwenLiu** [comment]
已解决
