### ISSUE TITLE
自然语言运算 > 项目：机器翻译 > 3. 自然语言处理机器翻译 Workspace - notebook错误

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#146]
## 课程导航+地址
自然语言运算 > 项目：机器翻译 > [3. 自然语言处理机器翻译 Workspace](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/30f31cf9-74bd-4764-a223-ea2967820ac7/concepts/b7226898-22d9-46ea-bafc-28f166c632ea#)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/uXjcowk18UiURDSOuyV-s5Uq8qd16IFXib9-mpzSY4WYrIjzZ7wH3goGRoWOvkO1YRo3hx26Vx6qwtRdtMvW7nsaVqBKeAXa1Xt3Zrg2XDtCvcLXYhnjTjtMA7p0ScUEVSfZTYqDNzZj3XsjHtR9KTPWsPEXTxjisv4GcsHRIjnY1M3-MNpYqUthPB57KER40StYQgAPkcsLMWwI4aJ0ftOVUMjn7rlWzLCd_nzmkxAbIlwTAtLYTXWN2mU6iYyGVpkiH8M6B7lJp7GklppKRnagLWh3tmuiXbBB957Im9RJ_ixraxqLx6qC7dExA3TmqLkbWWup1exASYzkfcSy4ktWV8v6Ra7to2WAyJaU-HI2oSv3rNVbuImJQy_Gv4By2Ujz40zOQhPL1WZdIE-4swkxpQmagc0HZZnwsaPbZ3nH7YMR1KgRY3O1AMLKjd5SyaXhjCzEZ_9rS7VGry8cANf1RFKjYZHKvOkF6rBIMtn8QdXFs0qAUDLkr31q_OTT2ARc2WAvns6wPa5wLT94vcvI-q78b8RAZDNxCoj_XxtMIoNgYvAvJh2xzeP0LaAAOzACTwsBIoQ18OZSXK491_h_8qZiA51JrsIvBSCMcwbf1JpVeNrnmlZSXh1_N4MSB0RQJCFkGa_ZTRWwWExd-PKw=w2360-h960-no">

## 具体描述
在资料夹中没有找到中文版的notebook

**Comment by UdacityShuwenLiu** [comment]
已解决
