### ISSUE TITLE
自然语言运算 > 特征提取和嵌入 > [8. 深度学习的嵌入]：非英语字幕出现

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#147]
## 课程导航+地址
自然语言运算 > 特征提取和嵌入 > [8. 深度学习的嵌入](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/46c8506d-50a1-4de8-bd1c-18b47af15b20)

## 具体描述
视频0.01s处字幕de facto，法语词汇，可考虑改为 in fact

**Comment by ChengGoooo** [comment]
可是。。。。他确实读的de facto😂

**Comment by scanfyu** [comment]
我只是说一下问题 哈哈哈

**Comment by ChengGoooo** [comment]
那我就先不改了😳

**Comment by ChengGoooo** [comment]
那就先放着吧，中文翻译是对的，应该不阻碍理解的。
