### ISSUE TITLE
自然语言运算 > 特征提取和嵌入 > [8. 深度学习的嵌入]：字幕错位

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#148]
## 课程导航+地址
自然语言运算 > 特征提取和嵌入 > [8. 深度学习的嵌入](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/46c8506d-50a1-4de8-bd1c-18b47af15b20)

## 具体描述
视频13s处字幕：
你可以用词做算术 例如 woman - man + king =queen
需改为：
你可以对词语做算法 是不是很神奇

16秒处：
这难道不神奇吗？
需改为：
例如 女人 - 男人 + 国王 = 女王

**Comment by ChengGoooo** [comment]
Fixed at https://github.com/udacity/subtitles/commit/6242cecb09b8c1705f55fcebd7114a4530809ece

没有把算式中的名词翻译，我认为这样应该更容易和视频上的英文对应。

如果有异议欢迎再次开启这个 issue
