### ISSUE TITLE
自然语言运算> 循环神经网络> 循环神经网络的应用

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#151]
## 课程导航+地址
自然语言运算> 循环神经网络> [4.循环神经网络的应用](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/6d454d80-ea18-40cf-bc21-459ece28a5c5)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47723883-960fc600-dca9-11e8-9869-81278d158ec3.png)

## 具体描述
“自动手写生成”需要重新翻译一下

**Comment by yifangwang08** [comment]
感谢反馈！
