### ISSUE TITLE
自然语言运算> 循环神经网络> 循环神经网络(第二部分)

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#152]
## 课程导航+地址
自然语言运算> 循环神经网络> [12. 循环神经网络(第二部分)](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/37e5c026-5ec4-44ef-b3c8-ceb1c1532b8f)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47723957-c192b080-dca9-11e8-9d2e-b98e88843baa.png)

## 具体描述
方程式格式问题 

## 截图
![default](https://user-images.githubusercontent.com/13103405/47723971-ce170900-dca9-11e8-8819-d6ec4d419999.png)

## 具体描述
方程式格式问题

**Comment by yifangwang08** [comment]
感谢反馈！
