### ISSUE TITLE
自然语言运算> 循环神经网络> 基于时间的反向传播算法练习 1

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#153]
## 课程导航+地址
自然语言运算> 循环神经网络>  [20. 基于时间的反向传播算法练习 1](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/9528e9b5-7b59-49be-bbbc-fd3f3e697e55)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724041-f7379980-dca9-11e8-8941-a6ab5952180f.png)

![default](https://user-images.githubusercontent.com/13103405/47724048-f999f380-dca9-11e8-90d5-6d7693c87b59.png)

## 具体描述
选择错误答案，A对应的反馈。“s”在题目中大写，答案最好也大写，如果可以的话修改一下

**Comment by yifangwang08** [comment]
感谢反馈！
