### ISSUE TITLE
自然语言运算> 循环神经网络> 更多数学知识

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#154]
## 课程导航+地址
自然语言运算> 循环神经网络> [23. 更多数学知识](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/593835fd-09a7-44a3-a1fc-56dadb02b2ca)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724163-3665ea80-dcaa-11e8-9596-abf7517a42e1.png)

## 具体描述
第一个公式格式没有居中。第二个问题是，方程式编号错误，应该是“方程式53”，下面的每一个方程式序数都少了1

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724180-4382d980-dcaa-11e8-9e42-285ea7eac806.png)

## 具体描述
编号重复

**Comment by yifangwang08** [comment]
感谢反馈！

**Comment by yifangwang08** [comment]
感谢反馈！
