### ISSUE TITLE
自然语言运算> 循环神经网络> 循环神经网络总结

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#155]
## 课程导航+地址
自然语言运算> 循环神经网络> [24. 循环神经网络总结](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/d4a9bba6-9784-441e-b021-5510a14b46d4)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724239-6614f280-dcaa-11e8-9f91-9e0027b6dfb1.png)

## 具体描述
没有翻译

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724262-6e6d2d80-dcaa-11e8-9119-fc8e22a63136.png)

## 具体描述
方程式格式

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724273-75943b80-dcaa-11e8-8004-602c056e1d72.png)

## 具体描述
文本格式问题

**Comment by yifangwang08** [comment]
感谢反馈！
