### ISSUE TITLE
自然语言运算> 长短期记忆网络(LSMT)> 其他架构

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#156]
## 课程导航+地址
自然语言运算> 长短期记忆网络(LSMT)> [10. 其他架构](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/1c0c804d-f928-4a3c-ae44-b62699a8b1ec/concepts/f9f95dcb-bb0e-43d3-841c-9277c54207cb)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724425-c7d55c80-dcaa-11e8-8654-b99cbf55e139.png)

## 具体描述
第一个链接是个PPT，不是论文

**Comment by yifangwang08** [comment]
感谢反馈！
