### ISSUE TITLE
自然语言运算> 循环神经网络> 整个章节

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#157]
## 课程导航+地址
自然语言运算> 循环神经网络> [整个章节](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/74b9f15e-9214-44ff-a9b9-0a9d840eec64)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47724641-361a1f00-dcab-11e8-853e-f3ea9822553d.png)

## 具体描述
整个章节中，图片和公式都没有和图注对齐

**Comment by yifangwang08** [comment]
感谢反馈！
