### ISSUE TITLE
2.自然语言运算 > 课程3.神经网络简介 >【22.多类别交叉熵】> 字幕未翻译

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#158]
## 课程导航+地址
2.自然语言运算 > 课程3.神经网络简介 > [22.多类别交叉熵](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/a9641a7f-f6a1-4868-9bbc-77a55f8b94be)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47729982-2941ff00-dc9c-11e8-8353-2f010fecd854.png">

## 具体描述
视频02m39s处字幕 because the y_i_j being 01 未翻译

**Comment by yifangwang08** [comment]
感谢反馈！
