### ISSUE TITLE
2.自然语言运算 > 课程3.神经网络简介 >【25.梯度下降算法推导与实现】> 字幕错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#159]
## 课程导航+地址
2.自然语言运算 > 课程3.神经网络简介 > [25.梯度下降算法推导与实现](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/86dd3eb6-7912-4739-b4df-1ee1f33da0f0)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47730729-ba65a580-dc9d-11e8-839c-d99ad0d25286.png">

## 具体描述
视频51ss处英文字幕you，需改为new

**Comment by yifangwang08** [comment]
感谢反馈！
