### ISSUE TITLE
自然语言运算 > 回归 > 14 绝对值误差 VS 平方误差 第二个视频 翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#16]
## 课程导航+地址
自然语言运算 > 回归 > [14 绝对值误差 VS 平方误差](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/229237eb-f9fc-4d62-b708-561f162dd857) 第二个视频

## 截图
![image](https://user-images.githubusercontent.com/12591144/46902458-93743a80-ce7a-11e8-9013-d4ee99f4a504.png)

## 具体描述
视频1s处字幕 这是个技巧的测试，需改为 这是个略有难度的测试

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个视频的中文字幕在字幕包里没找到，麻烦你看下哈~

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
