### ISSUE TITLE
 嵌入与 Word2vec >3.实施Word2Vec> 课程内容太长、语速太快、太难让人学习

### ISSUE THREAD

**Issue by Sampson91** [udacity/cn-nlp-issue-report#160]
## 课程导航+地址
 嵌入与 Word2vec >3.实施Word2Vec> 课程内容太长容易、语速太快、太难让人学习

## 截图
![_20181031132846](https://user-images.githubusercontent.com/7878063/47768218-0c481300-dd12-11e8-9ecc-6b63b96d4c7f.png)

## 具体描述
整个视频长达12分钟，课程内容语速太快，在我学习的所有内容中很少超过5分钟的

**Comment by yifangwang08** [comment]
感谢反馈！
