### ISSUE TITLE
自然语言运算>长短期记忆网络(LSTM)>9.组合在一起

### ISSUE THREAD

**Issue by Sampson91** [udacity/cn-nlp-issue-report#161]
## 课程导航+地址
自然语言运算>长短期记忆网络(LSTM)>9.组合在一起

## 截图
![qq 20181031161231](https://user-images.githubusercontent.com/7878063/47774737-c6e31000-dd28-11e8-9ce8-6e1f0f777f5e.png)

## 具体描述
视频56s处字幕：这只是个抽象结构，需改为：这是个任意结构

**Comment by yifangwang08** [comment]
感谢反馈！
