### ISSUE TITLE
2自然语言处理> 课程5：实现梯度下降 >【1.平方平均简介误差函数】> 文字翻译

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#162]
## 课程导航+地址
2自然语言处理> 课程5：实现梯度下降 > [1.平方平均简介误差函数](https://classroom.udacity.com/nanodegrees/nd113-cn/parts/d495d366-e13e-4be2-99fb-034055b0fe6d)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47796968-5e178a00-dd60-11e8-9272-f3932eed0b92.png">

## 具体描述
令我兴奋的是，改为令人兴奋的，语句通顺些

**Comment by yifangwang08** [comment]
感谢反馈！
