### ISSUE TITLE
2自然语言处理> 课程5：实现梯度下降 >【2.梯度下降】> 英文未翻译

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#163]
## 课程导航+地址
2自然语言处理> 课程5：实现梯度下降 > [2.梯度下降](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/0e07fafa-e796-4fab-b119-13f47f1d5c1b/concepts/7d480208-0453-4457-97c3-56c720c23a89)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47798652-c7e56300-dd63-11e8-91d5-ca91798c2ca0.png">

## 具体描述
Gradient descent steps to the lowest error 未翻译

**Comment by yifangwang08** [comment]
感谢反馈！
