### ISSUE TITLE
2自然语言处理> 课程5：实现梯度下降 >【7.反向传播】> 英文字幕符号

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#166]
## 课程导航+地址
2自然语言处理> 课程5：实现梯度下降 > [7.反向传播](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/0e07fafa-e796-4fab-b119-13f47f1d5c1b/concepts/87d85ff2-db15-438b-9be8-d097ea917f1e)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47801189-97ec8e80-dd68-11e8-8944-ac68736fe312.png">

## 具体描述
视频6s处字幕 去掉 > 符号

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
