### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [3. 分类问题]：国内可访问，下方依然文字通知

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#169]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [3. 分类问题](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/501ce6c5-9b80-4536-8754-f7da607fc40d)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47832523-ef264980-ddd0-11e8-9d60-ef212ea6fd55.png)

## 具体描述
页面上：
上方正确回答后弹出的视频为 youtube 的视频，在国内网络内可能会打不开。

下一节的视频内容即是这个解答视频

事实上：视频国内可访问。

**Comment by yifangwang08** [comment]
感谢反馈！
