### ISSUE TITLE
自然语言运算 > 回归 > 16 解数学方程表组 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#17]
## 课程导航+地址
自然语言运算 > 回归 > [16 解数学方程表组](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/ba95d332-6bae-45be-a642-649772712340)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46902620-29a96000-ce7d-11e8-9cb0-69e5b6cf305c.png)

## 具体描述
视频58s处字幕 我们计算倒数，需改为 我们计算导数

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个视频的中文字幕在字幕包里没找到，麻烦你看下哈~

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
