### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [8. 为何是“神经网络”]：字幕已修改，建议删除备注

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#170]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [8. 为何是“神经网络”](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/a3b18b18-8496-4775-af48-921ab35bd306)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47832815-8c35b200-ddd2-11e8-8bf3-3a085757589e.png)

## 具体描述
备注：视频28s处字幕“神经冲动”需改为“神经脉冲”
建议删除

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
