### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [10. 感知器技巧 - 计算机如何“学习”分类？]：备注未改动

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#171]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [10. 感知器技巧 - 计算机如何“学习”分类？](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/8ea20904-0215-4e44-afa9-bb5a720bd028)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47833281-e46db380-ddd4-11e8-8462-97a5dbfb1b13.png)

## 具体描述
57s处，“bias unti”应当翻译成“偏置单元”，而不是“偏差单元”；
未改动

**Comment by yifangwang08** [comment]
感谢反馈！
