### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [2. 简介]：备注未改动

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#172]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [2. 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/34148307-a49b-422c-b9bd-f6ac62bf35af)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47835975-5e0b9e80-dde1-11e8-95c2-656291540340.png)

## 具体描述
备注：视频0:15s处字幕“在危险游戏中检测垃圾邮件”，需改为“在邮箱中检测垃圾邮件”

未改动

**Comment by yifangwang08** [comment]
感谢反馈！
