### ISSUE TITLE
3. 自然语言交流> DNN语音识别 > VUI 语音识别器 Workspace

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#173]
## 课程导航+地址
3. 自然语言交流> DNN语音识别 > [5. VUI 语音识别器 Workspace](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/171b8584-8533-44b6-99dd-457045654800/concepts/f4f4ac78-d88a-40cf-80c1-60d9f8b742b3#)

## 截图
![default](https://user-images.githubusercontent.com/13103405/47849045-689b5780-de24-11e8-8102-5653325feabc.png)

## 具体描述
项目文件无法访问，我在外网无法访问项目文件

**Comment by yifangwang08** [comment]
感谢反馈！正常网可以访问
