### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [14. Logistic(对数概率)误差函数与梯度下降-初探]：备注未改动

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#175]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [14. Logistic(对数概率)误差函数与梯度下降-初探](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/5e1f6c71-6c75-4bb2-98a9-ee40c0eb3472)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47852780-c37a8200-de17-11e8-8222-97ee2c654889.png)

## 具体描述
备注：视频中所有的“罚值”更改为“惩罚值”，请不要误认为是“阈值”的错误写法

该备注未改动

**Comment by yifangwang08** [comment]
感谢反馈！
