### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [16. 多类别分类与Softmax 函数]：备注已修改

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#177]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [16. 多类别分类与Softmax 函数](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/9e1364a8-e8b4-4eac-be12-4d44a139f721)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47857192-f9256800-de23-11e8-8743-87f6e4be91d9.png)

## 具体描述
（备注：上方视频中文字幕1分44秒处的“不等于0”应修改为“不等于1”）

该备注已修改，建议删除备注

**Comment by yifangwang08** [comment]
感谢反馈！
