### ISSUE TITLE
2自然语言处理> 课程6:训练神经网络 >【14.动量】> 中文翻译

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#178]
## 课程导航+地址
2自然语言处理> 课程6:训练神经网络 > [14.动量](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/d98afa37-4318-4203-9f99-4e2a64922bee)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47857305-41448a80-de24-11e8-97e2-c1c1077de7fc.png">
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47857426-8d8fca80-de24-11e8-966e-ae4d9acc3845.png">

## 具体描述
视频1m20s处字幕β2，需改为β平方 更易于理解
 视频1m23s处字幕β3，需改为β立方

**Comment by yifangwang08** [comment]
感谢反馈！
