### ISSUE TITLE
2自然语言处理> 项目：你的第一个神经网络 >【3.项目】> 步骤顺序与文件名 

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#179]
## 课程导航+地址
2自然语言处理> 项目：你的第一个神经网络 > [3.项目](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/4c03fd28-20ca-40e6-89cc-e72ae96141c2/project)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47858306-bd3fd200-de26-11e8-967f-ce8aa0818636.png">

## 具体描述
下载下来的notebook已不叫 dlnd-your-first-neural-network.ipynb，
而是 Your_first_neural_network.ipynb

**Comment by yifangwang08** [comment]
感谢反馈！
