### ISSUE TITLE
自然语言运算 > 回归 > 6. 绝对值技巧 - 翻译问题

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#18]
## 课程导航+地址
自然语言运算 > 回归 > [6. 绝对值技巧](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/73940af7-d358-4b4a-b854-02f2888ded01)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/kae_UIPF3k6E_ZVgRzh98LCI_aX2ZV9oYKILW0jZm60bWhxD4tMawykb9m9nvq8dZw9NK55ABcmuZoouY8bN3dQL306piI-MDOymNuuFtK_MmsjvSBNqlhDcRsngKcru_nPSrPRZmhwCf_qWoN_MkywPT6Y_ZhEaETxQ89XZu_5XMyiWpQvCnwfn5opG5MRVnAHiAGWnl3Ua9AezxUzhjaPHYZWABd1RFdY_vdVWOGVEwUfYuyXPHvOn3tiecquKCE6qMW8KWJTeMz3tUgmlOIbCNlD2atdiku1yu9ilRLDT6rNhOWN2RMerPZHX2CatWG0PbHZQP0De3EttN6-12Gtr1qY3EmwUzCeSCN4UWMlayEcQlsMQDwxdA1E0JD7ip6uGIpyD-trpq4vRd-UHVdCzNAJuokc5ijmfQ5fbrxvHWMyouMV0uZZUrwlRQAzSvvKiiV4XpU6-gullBc3rnXg16hRPQPYFpVTesp_keL3SExORBASr3xZoEBxvFR5B6y2YuCtgov_SPDpDKHq-ndfJco4Rakt2MkNBvnQO5Do_AXUHmE0L25AaQDvYUAIahnMscwi0MRhgB9cLBGCiw68U-HM3cnaZ3w7EQDzyvFtJZ9QuoKdY_DdOw-D6OYQ=w1858-h1062-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Qfwgo5UOC71NNL4VzyQDEtwuhsmntRxR2CF2Ey3DP_U6tJpGGUtkY5ASOvM4Kf2vO4T5UAUV1NjcUrfAUYLNQJvbLM3gcNJRa5ohv8hc05A_EnIiWUPFN6EUu4Gexb0sH-bQfqx5u0gtyDLvSv8ZdbkjudTXajnX4W0QEESF3Zzbhf4avCBqpiljkSh-Rq9SHJzT9ayNJ29rn9X9t6IiiLPDWsLGibXfa4utEfaDw_4z_4-Fsytf7sSM0CkCOT0BYbsonqy2mbFNVyWcCbqupzt8pCRdNc0V98zPyPHhNpf30TMhFFrYz6m8L3x8j-lP1k8OBvnC5npRvQEt9fnbwXkspJ7v7ktfsrux9iHDCVk22OYGEIBHf8Z76rtck9eq7lHgA7QIKRhrQmyIAsvUQ-Nmh4uSm7MgbSe8GRxlm8fx9xqa-OIfhdSs9dDhWWtokqdBEaFlN1JpQ9mu4PE3xQIkmUW6csekVKT8vo6mHo4ZPXyGFzp0MN8P35nFHmu3QttRTtCg-GoqzTmfVymUEKX5QgmA9rGb6-vIXuAMoeoldyS4cwF0dwQTZHte2qxxFQFOnbhQtKHY2CMSpTuiWtDvIQTFLAN4cyuTCes4CrGr1jBiPxmQgHQkOrwS_ZE=w1860-h1066-no">

## 具体描述
视频0s至2s处的两页字幕 「所以这是我们第一个技巧 移动直线」 和 「更加靠近我们将在线性回归中使用到的一个点」，需改为 「所以这是我们第一个技巧来移动直线更加靠近点」和「 而这个技巧将被使用在线性回归中」

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个视频的中文字幕在字幕包里没有找到，麻烦你看下哈~

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
