### ISSUE TITLE
2.自然语言运算 > 课程9：TensorFlow > 【1.介绍】> 文字错误

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#180]
## 课程导航+地址
2.自然语言运算 > 课程9：TensorFlow > [1.介绍](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/299af9c1-2ec7-4055-bdf9-5248ead9490d/concepts/850460aa-9568-401c-9eed-b38cc1913fc4)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47858590-638bd780-de27-11e8-9409-ba0651a712bc.png">

## 具体描述
Keras 中间多余空格

**Comment by yifangwang08** [comment]
感谢反馈！
