### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [21. 交叉熵 2-损失函数]：备注问题

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#181]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [21. 交叉熵 2-损失函数](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/760235e0-a3ec-4e56-8cdb-56d762886690)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47858669-8b7b3b00-de27-11e8-8f72-23fe27c363d0.png)

## 具体描述
视频下方备注：
片中2'19''开始的描述改成“概率高的事件交叉熵低，而概率低的事件交叉熵高”

1、该备注未改动；
2、时间是从2`11``开始

**Comment by yifangwang08** [comment]
感谢反馈！
