### ISSUE TITLE
2.自然语言运算 > 课程9：TensorFlow > 【11.TensorFlow实验准备】> 链接404 

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#183]
## 课程导航+地址
2.自然语言运算 > 课程9：TensorFlow > [11.TensorFlow实验准备](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/299af9c1-2ec7-4055-bdf9-5248ead9490d/concepts/d62b83c5-e19e-4573-bfbb-c4fa8e9482e4)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47859515-769fa700-de29-11e8-8cb0-e339d1a0227e.png">

## 具体描述
- 1.小节课程标题错误：TensorFlow 写成了 Tensorlow，12小节也有此问题
- 2.我们的课程 链接 404

**Comment by yifangwang08** [comment]
感谢反馈！
