### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [23. Logistic 回归]：视频中公式

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#184]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [23. Logistic 回归](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/a5711d6e-abc1-41bc-a242-e8c8a9834f72)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47860150-d8acdc00-de2a-11e8-8fdb-5336e7befc69.png)

## 具体描述
视频 13s 处视频中的公式需改为-log(0.6) - (log0.2) - log(0.1) - log(0.7) = 4.8，右侧log(0.7) - (log0.9) - log(0.9) - log(0.6) = 1.2。

**Comment by scanfyu** [comment]
##截图
![image](https://user-images.githubusercontent.com/3198940/47860503-a2bc2780-de2b-11e8-8554-cb48e079a101.png)

##具体描述
中文字幕中包含英文

**Comment by scanfyu** [comment]
## 具体描述
视频 3分11秒 处视频中的中文字幕“这里yi是点x(i)的标签”应改为“这里i是x(i)的下角标”。

备注未修改

**Comment by yifangwang08** [comment]
感谢反馈！
