### ISSUE TITLE
2自然语言处理> 课程3：神经网络简介 > [28. Logistic(对数概率)感知器和梯度下降]

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#186]
## 课程导航+地址
2自然语言处理> 课程3：神经网络简介 > [28. Logistic(对数概率)感知器和梯度下降](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7a4e2b87-7f0b-45db-9b7f-19232bbac41f/concepts/1f6bbd8c-bb45-4e5e-b790-1ab0dad751e1)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47861978-0b58d380-de2f-11e8-9315-79c53c9385e7.png)

## 具体描述
备注“视频 00:13 处”，目前字幕正确，建议删除备注，此时上方视频中（相同）公式有误。

视频 1:06 左侧公式应该是w_{i}：该备注在本视频中未找到。

视频里的i表示的是x的第i个特征。

**Comment by yifangwang08** [comment]
感谢反馈！视频1：06备注中指的是to前的 i 是下标。
