### ISSUE TITLE
2.自然语言运算 > 课程10：Keras > 【6.IMDB数据】> 文字

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#187]
## 课程导航+地址
2.自然语言运算 > 课程10：Keras > [6.IMDB数据](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/5e22aa8d-9d4d-4b83-8b34-9f606d0abee4)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47862679-a56d4b80-de30-11e8-8e45-62d46ab54dc4.png">

## 具体描述
并不需要在文件夹中打开，文件已在根目录

**Comment by yifangwang08** [comment]
感谢反馈！
