### ISSUE TITLE
2.自然语言运算 > 课程5：实现梯度下降 > [5. 实现梯度下降]：链接指向英文版页面

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#189]
## 课程导航+地址
2.自然语言运算 > 课程5：实现梯度下降 > [5. 实现梯度下降](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/0e07fafa-e796-4fab-b119-13f47f1d5c1b/concepts/4b167ce0-9d45-45e1-bfe6-891b2c68ac94)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47886573-d9b72b00-de75-11e8-9759-03562864da4a.png)

## 具体描述
dummy variables的链接指向英文版维基百科。

**Comment by yifangwang08** [comment]
感谢反馈！该内容目前只有英文版
