### ISSUE TITLE
1.自然语言处理入门 > 课程3.自然语言处理简介 > [2. 自然语言处理概述]：字幕翻译

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#19]
## 课程导航+地址
自然语言处理入门 > 课程3.自然语言处理简介 > [2. 自然语言处理概述](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/e79dd351-a1d3-426d-a259-bf8cf9a26a98/concepts/862291a6-df26-4ef8-9c44-04e278de3dcb)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46902727-93b51a00-cefc-11e8-9914-049ff5eac6e5.png)

## 具体描述
视频25s处字幕“思考”，需改为“考虑一下”

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46902927-20150c00-cf00-11e8-8808-2a80da4d35c8.png)

## 具体描述
视频50s处，建议改为“但仍有漫漫长路要走”

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46902944-6ff3d300-cf00-11e8-8d5b-bf4961ace907.png)

## 具体描述
视频52s处，“这是它为什么是一个令人振奋但又在持续发展的学术领域的原因”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
