### ISSUE TITLE
2.自然语言运算 > 课程5：实现梯度下降 > [6. 多层感知器]：链接指向英文课程

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#191]
## 课程导航+地址
2.自然语言运算 > 课程5：实现梯度下降 > [6. 多层感知器](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/0e07fafa-e796-4fab-b119-13f47f1d5c1b/concepts/7d0a1958-be25-4efb-ab81-360d9aa4f764)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47887901-b93e9f00-de7c-11e8-852f-6109af9d7a9b.png)

![image](https://user-images.githubusercontent.com/3198940/47887970-f4d96900-de7c-11e8-8d77-de185cb5df0c.png)

## 具体描述
向量入门、矩阵入门均指向英文版页面。

矩阵乘法链接指向英文版维基百科。

**Comment by yifangwang08** [comment]
感谢反馈！

**Comment by yifangwang08** [comment]
课程都是英文视频，矩阵乘法链接已指向中文版维基百科
