### ISSUE TITLE
2.自然语言运算 > 课程9：TensorFlow > [5. 练习：TensorFlow 数学]：链接404

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#193]
## 课程导航+地址
2.自然语言运算 > 课程9：TensorFlow > [5. 练习：TensorFlow 数学](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/299af9c1-2ec7-4055-bdf9-5248ead9490d/concepts/0a2cb9ef-1537-4e07-9aa5-e4d07f82122d)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47890021-d462dc00-de87-11e8-8902-40765564ce42.png)

## 具体描述
标注位置链接无法访问。

**Comment by yifangwang08** [comment]
感谢反馈！
