### ISSUE TITLE
2.自然语言运算 > 课程9：TensorFlow > [11. Tensorlow 实验准备：NotMNIST]：链接404

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#194]
## 课程导航+地址
2.自然语言运算 > 课程9：TensorFlow > [11. Tensorlow 实验准备：NotMNIST](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/299af9c1-2ec7-4055-bdf9-5248ead9490d/concepts/d62b83c5-e19e-4573-bfbb-c4fa8e9482e4)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47890779-5b658380-de8b-11e8-9a98-e1c868297de0.png)

## 具体描述
我们的课程：链接指向404

**Comment by yifangwang08** [comment]
感谢反馈！
