### ISSUE TITLE
2.自然语言运算 > 课程9：TensorFlow > [15. TensorFlow 中的深度神经网络]：翻译不一致

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#195]
## 课程导航+地址
2.自然语言运算 > 课程9：TensorFlow > [15. TensorFlow 中的深度神经网络](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/299af9c1-2ec7-4055-bdf9-5248ead9490d/concepts/83a3a2a2-a9bd-4b7b-95b0-eb924ab14432)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47890838-ad0e0e00-de8b-11e8-94a6-c0480d6c8454.png)

## 具体描述
独热码，最好还是 one-hot 编码，第一眼看着没看懂说什么。

**Comment by yifangwang08** [comment]
感谢反馈！
