### ISSUE TITLE
2.自然语言运算 > 课程10：Keras > [4. Keras 中的优化程序]：博文链接无法访问

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#197]
## 课程导航+地址
2.自然语言运算 > 课程10：Keras > [4. Keras 中的优化程序](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/ff0ab4d8-5441-4d00-baa3-88735b503b76)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47892139-10e70580-de91-11e8-89f0-a9d71f6d46ac.png)

## 具体描述
博文链接经测试无法访问。

**Comment by yifangwang08** [comment]
感谢反馈！
