### ISSUE TITLE
1. 自然语言处理入门> 课程2. 文本处理 > 3.GPU Workspace 简介

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#198]
## 课程导航+地址
1. 自然语言处理入门> 课程2. 文本处理 > [3.GPU Workspace 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/8b7e602a-4a29-4009-b162-73c6051d4647)

## 截图
![default](https://user-images.githubusercontent.com/13103405/48124237-ef8e7b00-e2cf-11e8-9b94-1737d2ebbcc8.png)

## 具体描述
文本格式错误

**Comment by yifangwang08** [comment]
感谢反馈！

**Comment by yifangwang08** [comment]
感谢反馈！
