### ISSUE TITLE
1. 自然语言处理入门> 课程3. 利用朴素贝叶斯的垃圾邮件分类器 > 7. 参考答案：误报

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#199]
## 课程导航+地址
1. 自然语言处理入门> 课程3. 利用朴素贝叶斯的垃圾邮件分类器 > [7. 参考答案：误报](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/788c54ce-55de-4a1d-abae-0ad1ec6a0591/concepts/f24e7f09-fe5b-4f9f-bfbb-991692fe4bb4)

## 截图
![default](https://user-images.githubusercontent.com/13103405/48174425-14303480-e35c-11e8-9eb3-3234b3fa554f.png)

![default](https://user-images.githubusercontent.com/13103405/48174617-d5e74500-e35c-11e8-9523-a81250928126.png)

## 具体描述
字幕错误, 0:42s 和 3:40s处

**Comment by yifangwang08** [comment]
感谢反馈！
