### ISSUE TITLE
字幕翻译建议

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#2]
## 课程导航+地址
课程1 > 概念 > [1. 欢迎学习自然语言处理纳米学位课程](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/b1084f71-9949-4439-93e6-1550d86ce1e9/concepts/a83edf41-de0f-4145-9f9f-4fc7e434f752)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46868096-cbb75100-ce59-11e8-81bf-69c3fe130f14.png)
![image](https://user-images.githubusercontent.com/3198940/46868106-d4a82280-ce59-11e8-8188-80e86745860c.png)

## 具体描述
视频24s处字幕“学习这门课，就表明你也加入了这场变革之中”，建议改为“通过这门课的学习，你也能成为这场变革的参与者”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
