### ISSUE TITLE
自然语言运算 > 回归 > 19 多项式回归 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#20]
## 课程导航+地址
自然语言运算 > 回归 > [19 多项式回归](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/f67c8f75-858e-499a-9a8b-52740ce067d1)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46902815-c02b5080-ce80-11e8-9cc4-8a8427de0713.png)

## 具体描述
视频8s处字幕 可能是直线，需改为 可能是（曲）线

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
