### ISSUE TITLE
1. 自然语言处理入门> 课程3. 利用朴素贝叶斯的垃圾邮件分类器 > 9. 贝叶斯学习2

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#200]
## 课程导航+地址
1. 自然语言处理入门> 课程3. 利用朴素贝叶斯的垃圾邮件分类器 > [9. 贝叶斯学习2](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/788c54ce-55de-4a1d-abae-0ad1ec6a0591/concepts/388ba7dc-be7c-4417-9f1f-56abfd0b8451)

## 截图
![default](https://user-images.githubusercontent.com/13103405/48197416-c93d0e00-e3a9-11e8-92a3-031ea2d06671.png)

## 具体描述
50s处字幕错误

**Comment by yifangwang08** [comment]
感谢反馈！
