### ISSUE TITLE
2.自然语言运算 > 2.特征提取和嵌入 > 7.GloVe

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#201]
## 课程导航+地址
2.自然语言运算 > 2.特征提取和嵌入 > [7.GloVe](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/f3efc741-c87f-4af2-99fd-cc0b82ccc2f5)

## 截图
![default](https://user-images.githubusercontent.com/13103405/48818002-f3b4a100-ed83-11e8-998c-2aff7092d1c6.png)

## 具体描述
翻译需要更改为，“你在ice的语境中比steam的语境中更容易想到solid”

**Comment by yifangwang08** [comment]
感谢反馈！翻译是断句的问题。在“相比 steam”后断句，就不会理解错了
