### ISSUE TITLE
自然语言运算 > 回归 > 20 正则化 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#22]
## 课程导航+地址
自然语言运算 > 回归 > [20 正则化](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/3f69dcbd-dc3b-4e6d-a1cc-3257db6ce3c0)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46902905-282e6680-ce82-11e8-82a2-77edfdc171f3.png)

## 具体描述
视频3:54s处字幕 所以我们得到 2 的平方加 2 的平方加上 4 的平方 ，需改为 所以我们得到 2 的平方加 **-2** 的平方加上 **-4** 的平方

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个视频的字幕在字幕包里没找到，麻烦你看一下~

**Comment by sylviasun916** [comment]
已修改 感谢反馈
