### ISSUE TITLE
自然语言处理入门 > 课程3.自然语言处理简介 > [3. 结构化语言]：字幕翻译

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#23]
## 课程导航+地址
自然语言处理入门 > 课程3.自然语言处理简介 > [3. 结构化语言](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/e79dd351-a1d3-426d-a259-bf8cf9a26a98/concepts/2b13e2e4-8ef8-45bd-8cb2-1e299573ddc5)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46902999-5dc66480-cf01-11e8-98db-47af6de5b8da.png)
![image](https://user-images.githubusercontent.com/3198940/46903001-6323af00-cf01-11e8-9096-f23fdcf3b3a1.png)
![image](https://user-images.githubusercontent.com/3198940/46903028-c57caf80-cf01-11e8-9756-11fb7071edf5.png)

## 具体描述
视频6s处字幕“人类语言的一大缺陷，依赖于你观察方法的特征”，
改为“人类语言的一大缺陷，或者你如何理解语言所用的特征，是缺乏一个准确的概念结构”

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46903098-d4179680-cf02-11e8-80fc-c7d4eb99c0ab.png)

## 具体描述
30s，“形式逻辑也使用结构化的语言”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
