### ISSUE TITLE
自然语言运算 > 回归 > 21 神经网络回归 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#24]
## 课程导航+地址
自然语言运算 > 回归 > [21 神经网络回归 ](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/5cb5938c-cf31-4749-88ca-32ee7b5f6bb2)

## 截图 1
![image](https://user-images.githubusercontent.com/12591144/46902978-552f4900-ce83-11e8-9019-9962e98999e6.png)

## 具体描述
视频12s处字幕 我们可以使用老功能 神经网络，需改为 它对我们来说已经不陌生了 神经网络

good old friend 翻成老朋友 老伙计 老功能 念起来都会感觉有些尴尬

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46902987-611b0b00-ce83-11e8-8632-13235183a660.png)

## 具体描述
视频12s处字幕 这是个很有趣的事情，需改为 这是个振奋人心的消息

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个视频的中文字幕在字幕包里未找到，麻烦你看一下~

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
