### ISSUE TITLE
自然语言运算 > 评判标准 > 1. Intro 未翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#25]
## 课程导航+地址
自然语言运算 > 评判标准 > [1. Intro](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/b9fb849d-bc1e-41e6-adde-1c41da896495)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46903111-4c3f7700-ce85-11e8-8d8e-ff6c9d93c370.png)

## 具体描述
貌似漏翻译了 先试一下吧

目前为止，我们学会了如何训练神经网络以及如何优化它们的训练。我们还需要知道如何适当地评判它们的行为。为此，我们将会使用一些非常有用的指标。
在这一节课里，我们将会学到一些最常用的、用于深度学习以及普遍性机器学习的评判标准。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
