### ISSUE TITLE
自然语言处理入门 > 课程3. 自然语言处理简介 > [4. 语法]：MD语法

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#26]
## 课程导航+地址
自然语言处理入门 > 课程3. 自然语言处理简介 > [4. 语法](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/e79dd351-a1d3-426d-a259-bf8cf9a26a98/concepts/de90f175-ffea-4171-a082-da9ca71517b2)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46903593-d6312380-cf09-11e8-90f6-a9c1d363f7b9.png)

## 具体描述
Markdown语法有误。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
