### ISSUE TITLE
1.自然语言处理入门 > 课程4.文本处理 >【1.文本处理】> 翻译问题

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#29]
## 课程导航+地址
例子：1.自然语言处理入门 > 课程4.文本处理 > [1.文本处理](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/14924ea9-7fd9-4eed-8933-5e6e3b25ac65)

1.自然语言处理入门 > 课程4.文本处理 > [8.标准化](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/0b78d3e2-37dc-4888-b3d3-ea6ff69b623e)  中 43s 处也有此问题

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46906346-ae0aea00-cf34-11e8-845f-751680797dc0.png">

## 具体描述
视频19s处字幕 tokens 翻译为 令牌 不妥
words 和 tokens 可都指代 词 的意思

 NLP 从文本中提取含义（meaning）的一种方法是分析单个单词。将文本分解成单词的过程称为tokenization——产生的单词称为token（tokens）。标点符号也是tokens。

**Comment by yifangwang08** [comment]
感谢反馈！
