### ISSUE TITLE
课堂链接需科学上网+翻译建议

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#3]
## 课程导航+地址
课程1> 概念 > [2. 截止期限规定](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/b1084f71-9949-4439-93e6-1550d86ce1e9/concepts/5b238258-09bf-4923-b196-b1429e36a723)

## 截图

![image](https://user-images.githubusercontent.com/3198940/46869046-1ab2b580-ce5d-11e8-8ede-a78ebf628fbc.png)

## 具体描述
课堂提供的链接需科学上网才可以访问。

8月班次下方：（对应链接）
下载这个建议的项目截止期限 ICS 文件并将其导入任何所选日历中。（https://calendar.google.com/calendar/ical/knowlabs.com_2spt5fjca10ko88q0lnibmrkvs%40group.calendar.google.com/public/basic.ics）
打开这个建议的项目截止期限 Google 日历并点击右下角的 + 按钮。（http://bit.ly/2OhT6EB）

7月班次下方：（对应链接）
下载这个建议的项目截止期限 ICS 文件并将其导入任何所选日历中。
打开这个建议的项目截止期限 Google 日历并点击右下角的 + 按钮。

6月班次下方：（对应链接）
下载这个建议的项目截止期限 ICS 文件并将其导入任何所选日历中。
打开这个建议的项目截止期限 Google 日历并点击右下角的 + 按钮。

5 月班次下方：（对应链接）
下载这个建议的项目截止期限 ICS 文件并将其导入任何所选日历中。
打开这个建议的项目截止期限 Google 日历并点击右下角的 + 按钮。

4 月班次下方：（对应链接）
下载这个建议的项目截止期限 ICS 文件并将其导入任何所选日历中。
打开这个建议的项目截止期限 Google 日历并点击右下角的 + 按钮。

这里的翻译： 这里上边表中是“建议的截止期限”下边翻译为了避免重复又改为提倡，不是特别合理。
强烈建议将这些提倡的截止期限添加到日历中，以便跟上进度。
建议改为：
强烈推荐将这些建议的截止期限添加到日历中，以便跟上进度。

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，我不太懂这个 issue 是什么意思，麻烦你看下看是否需要做修改。若是不需要修改的话可以直接关掉~

**Comment by scanfyu** [comment]
> @UdacityShuwenLiu 淑雯，我不太懂这个 issue 是什么意思，麻烦你看下看是否需要做修改。若是不需要修改的话可以直接关掉~

反馈页面内提供的链接需要科学上网才可以访问。

**Comment by UdacityShuwenLiu** [comment]
@yifangwang08 没有找到这个concept在哪里 QAQ

**Comment by ChengGoooo** [comment]
已确定删除此部分内容，添加中国区的服务部分。
