### ISSUE TITLE
1.自然语言处理入门 > 课程4.文本处理 >【6.捕获文本数据】> 字幕问题

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#30]
## 课程导航+地址
例子：1.自然语言处理入门 > 课程4.文本处理 > [6.捕获文本数据](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/12fe2c2a-3d52-491f-a87c-8e1970541848)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46906601-9e8da000-cf38-11e8-82a6-3f4186aa1dbc.png">

## 具体描述
视频24s处字幕 SCV，需改为 CSV

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
