### ISSUE TITLE
自然语言运算 > 评判标准 > 2. 混淆矩阵

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#31]
## 课程导航+地址
自然语言运算 > 评判标准 > [2. 混淆矩阵](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/2034dd12-8ffc-4753-b8f4-c6042487ea5d)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46908809-38bffa80-cedd-11e8-8ba7-30471efd05f9.png)

## 具体描述
上述模型有多少真正例、真负例、假正例、假负例？

这些术语都是第一次出现 而且与视频中的字幕不一致 我感觉应该改为

上述模型有多少真阳性、真阴性、假阳性、假阴性？

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
