### ISSUE TITLE
自然语言运算 > 评判标准 > 9. 精度 答案翻译缺失

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#32]
## 课程导航+地址
自然语言运算 > 评判标准 > [9. 精度](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/dd22bf82-f166-4355-b53f-98c482f63699)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46910136-2ac9a400-cef4-11e8-8cbe-0c207c8cf81f.png)

## 具体描述
答案没有翻译 而且似乎有多余的链接 看起来像是markdown的错误

精度： 在所有我们预测的阳性结果中，有多少是正确的？
精度 = 真阳性 / （真阳性 + 假阳性）

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个 issue 是图片缺少翻译，添加翻译需要更改图片，麻烦你看下（里面提到的多余链接应该是针对非VPN打不开图片的问题添加的）

**Comment by sylviasun916** [comment]
已添加学员建议的翻译。

**Comment by sylviasun916** [comment]
感谢反馈！
