### ISSUE TITLE
自然语言运算 > 评判标准 > 10. 召回率 答案翻译缺失

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#33]
## 课程导航+地址
自然语言运算 > 评判标准 > [10. 召回率](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/944ae914-395f-4e65-a5f3-0ac24593c861)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46910213-687afc80-cef5-11e8-8d0a-c3eb29ed355e.png)

## 具体描述
答案的解释似乎没有翻译

召回率：在所有标记为阳性的点中，那些是我们正确预测到的
召回率 = 真阳性 / （真阳性 + 假阴性）

**Comment by yifangwang08** [comment]
感谢反馈！
