### ISSUE TITLE
自然语言处理入门 > 4.文本处理 > [4. Workspace：最佳做法]：MD语法错误

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#34]
## 课程导航+地址
自然语言处理入门 > 4.文本处理 > [4. Workspace：最佳做法](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/c9eb89f9-e2d9-4969-898a-c738a7721e88)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46911671-d37c1000-cf95-11e8-9b35-f89524cb7cd7.png)

## 具体描述
Markdown语法错误

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46911698-5735fc80-cf96-11e8-9c07-feeb9e16afc2.png)

## 具体描述
链接指向英文版维基百科地址。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
