### ISSUE TITLE
自然语言处理入门 > 4.文本处理 > [6. 捕获文本数据]：字幕翻译

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#35]
## 课程导航+地址
自然语言处理入门 > 4.文本处理 > [6. 捕获文本数据](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/12fe2c2a-3d52-491f-a87c-8e1970541848)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46911940-813ded80-cf9b-11e8-9177-56d2004c0abe.png)

## 具体描述
视频51s处字幕，“我们使用 Python 中的请求库”。
应该为“我们使用 Python 的 requests 库”。
该库名即为“requests”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
