### ISSUE TITLE
自然语言运算 > 循环神经网络 > 3. 循环神经网络历史 英文链接

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#36]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [3. 循环神经网络历史](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/7b7c1680-19e1-46c5-a48a-143ad051254c)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46913039-6edf9780-cf3a-11e8-83d1-f88d0fad15aa.png)

## 具体描述
链接均为英文链接 修改建议如下
[梯度消失](https://zh.wikipedia.org/wiki/%E6%A2%AF%E5%BA%A6%E6%B6%88%E5%A4%B1%E9%97%AE%E9%A2%98)
[等比数列](https://zh.wikipedia.org/wiki/%E7%AD%89%E6%AF%94%E6%95%B0%E5%88%97)
[时延神经网络](https://zhuanlan.zhihu.com/p/28283265)

其余的是论文原稿和个人主页 不翻译应该问题不大

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，你帮忙看下这个 issue 是否需要修改~

**Comment by UdacityShuwenLiu** [comment]
无需翻译哦，谢谢反馈
