### ISSUE TITLE
自然语言运算 > 循环神经网络 > 4. 循环神经网络的应用 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#37]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [4. 循环神经网络的应用](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/6d454d80-ea18-40cf-bc21-459ece28a5c5)

## 截图 1
![image](https://user-images.githubusercontent.com/12591144/46913150-dbf42c80-cf3c-11e8-9daf-975bf8979cf8.png)

## 具体描述
视频4s处字幕 为了让你了解有效的循环神经网络和长短期记忆网络，需改为 为了让你体会到循环神经网络和长短期记忆网络的强大

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46913157-f4fcdd80-cf3c-11e8-8392-afa8bfe1f58e.png)

## 具体描述
视频1:22处字幕 你听说过复选框吗，需改为 你听说过聊天机器人（chatbot）吗

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，根据视频里的 PPT 内容，确认是英文字幕出了问题。“Have you heard of checkbox?” 应改为 “Have you heard of chatbots?”（中文字幕我已经修改过了）

**Comment by sylviasun916** [comment]
已修改 感谢反馈！
