### ISSUE TITLE
自然语言运算 > 回归 > 13 实验：预测生命长度 - 缺失翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#39]
## 课程导航+地址
自然语言运算 > 回归 > [13 实验：预测生命长度](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/1f54aa7b-c5ca-4ab1-9575-fc9254f89335)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/VgE_qRZLeQC4H7wa4oIluPaI2RPzbizJy4P1cbMqfA2Y42WUFj62F4ubRTk9Whyjoj-By063CW89g7zRkxCR8E9NNanjMepXnvrcK3ord-mDu3kUjU-rL8hkjiRertjNX7al1dM950GAzGm1LixdpXUhVpUC5A67_JLJp26___KAY2lsEUIWmSKnh-xzV14lvaUbVs3b9itsJzB2K5EUSTppCqHoxBUkbjW74B-5hyn5rvnXMus3RmsBQo-IDWD1AjLOZluB-3TvUbIggwr8pkQbIP-tvZgIywXBYJ4AxHAwqU2TkOWEv6fCzQB1xgXtnSk7oIwxD8qHghSkwrYXzZwz3qqu7d56MFjQ1aAbtHBr3LmLnUd7q3GApmDUtMu2ImQ1GBT-LjS6jIpXU9OSvddf9sQv78fm5wh6QEhiuxFtCCZaPPcBfLZ_rP9Q86TuDQj1LxwBIai6DJJ-v2Fj5cR-RP-uwH1_8kgih-rmoVXEdtehnK5xjMyUL1c-aBV-dFOOzdjfV7f6u-TIOT_JddwiZaipXowhs8GYQb1-YJlHbATzFCcQ6a_kkChwjAnjt-v0kunh-9q32co_QXZ4QF9E5RpH1coxSv-zg4Q4kZzJ9NaaY-4IERpnftn8hms=w1944-h768-no">

## 具体描述
实验中notebook并没有翻译后的版本

**Comment by yifangwang08** [comment]
感谢反馈！
