### ISSUE TITLE
字幕翻译错误

### ISSUE THREAD

**Issue by Sampson91** [udacity/cn-nlp-issue-report#4]
## 自然语言交流>语言用户界面简介
例子：课程3>  [ 语言用户界面简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/798df1e9-f6c4-4b36-a50d-fb7ee7295a8e/concepts/cfbae6e2-d825-463d-995a-bd4cb4ad8102)
## 截图
![qq 20181012213242](https://user-images.githubusercontent.com/7878063/46872429-a5e47900-ce66-11e8-92ae-7d4bd59c1d6c.png)

## 具体描述
视频11:49s处字幕: 把这些观点转化成实践，需改为：来创建你自己的人工智能对话应用。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
