### ISSUE TITLE
自然语言运算 > 回归 > 16 解数学方程表组 - 注解错误

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#40]
## 课程导航+地址
自然语言运算 > 回归 > [16 解数学方程表组](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/5c80336e-78be-4ad4-9514-f8295c0ca620/concepts/ba95d332-6bae-45be-a642-649772712340)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/fyEPSagUCVcW9Pa7ktq2mGrb4fB2xibcvHgMNRbaMCzdW0D83MmFQ3a5nhjdlH9qEo2iSkt-iT5FdhpBn4ov_Y7cRyoOOBcx9li96LyAmse9wVNyRM-gVNOp5dJiEsK_bnqTnpunQZfV5ALYA7g_uVAVGAng_Y3Nakh7NDeJ7uUwEoym4meRIdU_uXnysH9ccn-pQdM-hsHXxECtpHGQwf98kXMlifIkWkJoKs9Exaq_xtvnipSSFYqQiPb-q_Guibm1kpI8XUHW0M3F15OEgjMo_gOJCtIyX1pXMUt2EmG0jkR5DTxj-6UPWPpCa0CZ99nt4uJYqPJfGfTSfUOLiLeGcGIpcPDgzLDktCT__ui__w7VhuQ9nhkZFtvmH7UEcfCaNsdBlSloOAISWyYrF7nHHUKPgVMZKk8MKOC8ncLuRiHXcqPY3XoLfyI-ILOai-A2YCkOQE68pfqV7uqvwWcCsay_a_N5yKQZiC5dPqHoe9XXuhjBG9SbccerZQiwdfuQdhus7I_W622Qcgojyts4lNhrACTN_WQLbKyzUU4f9tj-XAPaWztimY4dFZiRtr9dJi8vH5-STNrQz80q1PAGLNqLdaC0nauQ_Oa6H3v-zwhpY6KARunPZVzpY6k=w1334-h138-no">

## 具体描述
应将 「课程19.参考答案：解数学方程组中的方程式」 改为 「课程17.参考答案：解数学方程组」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
