### ISSUE TITLE
自然语言运算 > 循环神经网络 > 6. 前馈过程 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#42]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [6. 前馈过程](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/29a326a7-32b9-46bb-93aa-10a09acef7c0)

## 截图 1
![image](https://user-images.githubusercontent.com/12591144/46913824-79edf400-cf49-11e8-863c-43d727eaf7cb.png)

## 具体描述
视频33s处字幕 还有一个不同的矩阵，需改为 以及另一个权重矩阵

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46913845-cd604200-cf49-11e8-8c43-dad51d75fd2e.png)

## 具体描述
视频1:17处字幕 使用 softmax 函数是有益的
需改为 使用例如 softmax 函数是十分有帮助的

## 截图 3
![image](https://user-images.githubusercontent.com/12591144/46913876-7f980980-cf4a-11e8-874f-105f6e57c935.png)

## 具体描述
视频1:29处字幕 你可以在这个视频结束后查找文本中这个话题的更多信息
需改为 在看完这个视频后 你可以在下面的文字说明里了解更多关于这个课题的信息

## 截图 4
![image](https://user-images.githubusercontent.com/12591144/46913906-0b119a80-cf4b-11e8-8c75-0e4bf1086a18.png)

## 具体描述
视频2:58处字幕 我们有输入 n_x 和输出 m_h
需改为 我们有 n 个输入项 x 和 m 个输出项 h

## 截图 5
![image](https://user-images.githubusercontent.com/12591144/46913940-7d827a80-cf4b-11e8-8d03-346572fc02e1.png)
![image](https://user-images.githubusercontent.com/12591144/46913944-85dab580-cf4b-11e8-8a64-e1fe090a79b1.png)

## 具体描述
视频3:05处字幕 如果我们不处理输入 只是处理之前隐藏层的输出
deal with 感觉应该翻为 对待、面对
可以改为 如果我们面对的不是输入 而是上个隐藏层的输出

## 截图 6
![image](https://user-images.githubusercontent.com/12591144/46914009-7f990900-cf4c-11e8-8afd-b622ae2d6240.png)

## 具体描述
视频4:44处字幕 偏差保持不变 而其他输入会发生变化
需改为 当其他输入发生变化时 偏差保持不变

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
