### ISSUE TITLE
自然语言处理入门 > 4.文本处理 > [8. 标准化]：字幕翻译

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#43]
## 课程导航+地址
自然语言处理入门 > 4.文本处理 > [8. 标准化](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/0b78d3e2-37dc-4888-b3d3-ea6ff69b623e)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46914469-d0eadc00-cfd0-11e8-8170-3a1ca576dbed.png)
![image](https://user-images.githubusercontent.com/3198940/46914472-d811ea00-cfd0-11e8-9f26-f1d35a1e2e60.png)
![image](https://user-images.githubusercontent.com/3198940/46914475-de07cb00-cfd0-11e8-8302-edb8a3f53419.png)
![image](https://user-images.githubusercontent.com/3198940/46914476-e3651580-cfd0-11e8-9850-4f73946257eb.png)

## 具体描述
视频1m34s处字幕，需改为下方内容（长句时，内容与字幕不对应）

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46914578-69ce2700-cfd2-11e8-8ad5-e020ea7cd085.png)

## 具体描述
匹配那些不是小写A-Z的子母

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
