### ISSUE TITLE
自然语言运算 > 评判标准 > 1. Intro - 缺失翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#44]
## 课程导航+地址
自然语言运算 > 评判标准 > [1. Intro](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/b9fb849d-bc1e-41e6-adde-1c41da896495)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/L44W4kdsoIOnleF92Q-F5pKjHSOOGsbjBIuRNTqmTKIlyFSc_iI7Rzh4O4TCW35vdIyKnMUzhDl62Res_P-7eygRdQXPduGWRPYAkQsDLIafH7VyyFEcslETruH7AcKbIMG2A2XwZzvpX4MxncoilATob1QhKqX9iCBOhdLdTNUoNW3LGXv5dPWHws5mUEm2O9uKtnyjI8SjJBgzsOu_P19GytTprToq4ugwaKipPPUCAdnKwwXGUt6uKMVqKaumpq__TQi4dhS2LByT9SjtNgtaH99hh11cP6Wrn8npPwWw4omTwVx5w24LBmf2csIewu8jPN-Bwa1YMz1POjXbwr4iSY0tQZvtwwLtZctp11dllp3yUb_dQJxCqBrg_ewBaP6vBjNHIIodF-z9Y_9ehoyMTx9UeAXxnvgtDHEtPxUkaWa_VDuYgxbwXNqVSC0nCxNcABkbWwWoWtnBcatvhZ0kDbbIErv4t4MnLyMFl88jq12MFqUfoRinssTvsiWV_g5EEqvv_NIH5u0jnijPGVzG9C4ji9rzIPHT5PcVD91TDvU7_s58lMQey8dKaE8BSa7na3cHcaM6rcdmovSobZv4xj_3DmBaW-6dYDkMOXoeNuxAeeEuU16i8tIA5j0=w1468-h1110-no">

## 具体描述
以下是我的翻译

嗨，又见面了 ！
我们已经学习如何训练神经网络并且如何优化训练过程，现在我们还需要知道如何适当的衡量神经网络的行为。为此，我们将使用非常有效的衡量指标。在这个章节中，我们将学会一些在深度学习中常用的衡量指标，并且这些指标也是普遍用在机器学习领域中。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
