### ISSUE TITLE
自然语言处理入门 > 4.文本处理 > [9. 标记化]：翻译错位

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#45]
## 课程导航+地址
自然语言处理入门 > 4.文本处理 > [9. 标记化](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/771cd35e-2e0a-4e2b-b6b0-3987885dc71e/concepts/dd522917-2c5c-45a8-ad3f-34cead6c9ed0)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46914725-d4cc2d80-cfd3-11e8-9c2e-c6382fd9c518.png)
![image](https://user-images.githubusercontent.com/3198940/46914738-f6c5b000-cfd3-11e8-8a70-13d9984aa4e9.png)

## 具体描述
视频53s处字幕需改为：
但是使用诸如NLTK库，这样的一些操作就会简单许多
NLTK，也就是“自然语言工具包”的意思

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
