### ISSUE TITLE
自然语言运算 > 评判标准 > 2. 混淆矩阵 - 专业术语不一致

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#46]
## 课程导航+地址
自然语言运算 > 评判标准 > [2. 混淆矩阵](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/2034dd12-8ffc-4753-b8f4-c6042487ea5d)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/c7MYusHwEwDDnEE_DMvgG0okLyv8JBBwcPCzYH23ckyI6lSG9yNg-jUL9SIIn0thj1_uLyYoht236PnhFJ9W3uQdZTCQPFRpJdlpsWZjxZu-lqwTkxmbMrv6UDgLRggVaMrCD3FZ3ixUFXlrwTS7lxOOj1JWVP5YTeNFTKYm0mlA79dKeVkdinMfgYdPGBANpGApBSwmlryRTQ3-pq2ZBvsUHsrcR32sfU7Nb_VB7BUj8NFDw9MM56bRJcEInS3ztEXqQUaryY0Z-Ye3ObzF7k3GLqOU18YygY6j4x9gCOiEVwdcTNlv8JW8DeRTcm5iqOMOsP-uH6PaGdVel9XT9Ru6hiU_l_GOQ6w9JbV0WOUwAxMafFFKSxn7cpDjQ1ei6CxTh_LGwZIrqiWAcvaBtYpbGG-fIJcRJ3cOQxGb-2LgSsnlRqJVQxpVQ1rs-ORE_R7PqWi8ud1geIvz4d-ePJzpfd9Zc85HXt8KJPghvRo6isUTvOWQCRlSuxS2v0nE_MOy6jJPpa8FqJGMAUggEeqOZlclcTrTqgDfb1w8hTUBxD7h8gbwJmIDOL0HZWt-NvPEHHtBHvrbNrx7aY-EYQbYFakJAJliMNLYfPjOvQymEo_Roc4b16eZVSFb-xU=w1484-h546-no">

## 具体描述
问题中的 「真正例」、「真负例」、「假正例」、「假负例」
应改为和影片中一致的术语，「真阳性」、「真阴性」、「假阳性」、「假阴性」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
