### ISSUE TITLE
自然语言运算 > 评判标准 > 5. 准确率 2 - 章节名称建议

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#48]
## 课程导航+地址
自然语言运算 > 评判标准 > [5. 准确率 2](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/e8085600-b060-4486-adbb-f61b28a6fecc)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/TFJ6nHAx9DHnyra3Ntextz9ln7l_y6Yre0VTUr3EczO8N2byuH6sevkO73O9aYdTn3fmi0lPjxD6IIRx31mrWEY7VvWvywnY1LDj6_P3PyzTScMpfDV22Ktcrovpqr2UO30HoYbV9Cn9Ojzy91Uq4WJCQCJV-ieMJZ6fyj9tnKRsIP0BBKJQDPmdruS62TILjAna5RMgH3j7Gp3z_R8BMNqkPM16C5KXCwl4zR6Ducq2uujTL8kV4ifa-EV7ITXundPBAxGQlXCwmzQanbGlb6nARDIFFxJGoKiOtNjzVe9PGsPR6qKzZOeX4nrrDH4dIjtkHY1CZznKRfqRbcn1ek7JW6ZSPBi9RL_PQNAQVGqmcTny6b64e0IVc1LbXFSdazous2SSybRnDUVoZ4rcO_D3ppo9COJ-6IxnlPG-2kTst6LAtG20PJjtFnjWbeuIbord-N0-r57opnf4vycK69b8WZfRsqzhSabftjpFeayPM24sd8Jwl-OzqcnOBd37c9SiUgIoNIOh7-HVebZ-9RHMTYpw18XKHoXDswCPg-Mk7EOGxRsneH2utFm__0hm755Y583H6fcLvc9CSGNMwv0WXf_Rrt3hdBFYS5LmVZYwwP42XgYVr7YOOhIAJVM=w330-h204-no">

## 具体描述
根据内容，这个章节的名称应改为 「答案 - 准确率」

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
