### ISSUE TITLE
自然语言运算 > 评判标准 > 8. 答案 - 假阴性与假阳性 - 内容错误

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#49]
## 课程导航+地址
自然语言运算 > 评判标准 > [8. 答案 - 假阴性与假阳性](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/72f25a6a-d6f7-4dcb-894d-cdad9b060c35)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Eakx2H9YVojdW9gM4sZgvS4QTH1zU2_3ZsMDGtLcZjA_mSX16TNvx57rgVruhC9i91ReE970extzLc6Ho34ohw8HPW_JPMwp7vdg_VHPCII7doeJrAaJ5CYd-cIkH0Ku4ZNg7NKatA7znF9qqwuTKh3rJ5CDu4awwYMdiNS3jatpbN28KyvCTBdaNZIh6YJftplB82ihs3FNYYT_5pJEyhXLab2xmm1tOAt4igeNt4oHXcKh3GEQDNwg6hTdlk_zfk-0tZ0bVotYdcHHzbWOzDrpNM-w-zvvAZoU31hf5Y3-wZGs92yMjHCVzMaQU5PZCk8AfgOy55jg_k_8gxwv7JBolpbXMlzBpE5gGNpigRtBregt_YqxsQwv_zBKebSdCcolFad36zfqftG4CQVvsmUE284NHy-dH82Oz4I7OqVkqpA0kx5RY__XztAEMISqy0an9NCtw4xmO4P05GiRViKXPdFXxsdbE7ZLaCCDTFBeeiubjCEQ5HJ_lT-RaJl8WBI8H_xSZhfk_cu7LsnHlzp3t6AVEsW_XnQFCviZj0BCQxRuAmvbm2PtYLxguVXkp_v-8qTaNYYOc3nVR07jtW5qgh7eEt3a5Q_O1ODS95SuBdGwlcrWRunGIP-S24Y=w1528-h1168-no">

## 具体描述
视频13s处 根据问题的描述，在医疗问题下 「假阴性比假阳性情况更糟糕」，但讲师和字幕却说明「假阳性比假阴性更糟糕」

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个 issue 是英文视频的讲解错误导致的，暂时解决办法只能在 coco 里加个注释来说明一下

**Comment by sylviasun916** [comment]
@UdacityShuwenLiu  HI Shuwen, 这里的字幕与讲师讲解都是一致的，不过学员提出疑问，可能是我们的讲师讲错了。考虑到学科专业性，麻烦你看一下是不是讲师讲错了哦？ 如果是，我们可以在讲师注释里补充说明一下哦，如果无问题，也可以和学员解释一下, close ticket 哦，感谢！

**Comment by UdacityShuwenLiu** [comment]
讲师说的没有问题哦～

**Comment by yifangwang08** [comment]
感谢反馈！已修改~
