### ISSUE TITLE
1.自然语言处理入门 > 课程1.欢迎学习自然语言处理课程 >【3.社区指南】> 链接指向英文网站、需要翻墙

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#5]
## 课程导航+地址
例子：1.自然语言处理入门 > 课程1.欢迎学习自然语言处理课程 >[3.社区指南](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/b1084f71-9949-4439-93e6-1550d86ce1e9/concepts/cfaa3091-260b-4a3c-8049-d097749ddb57)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46871072-f6f26e00-ce62-11e8-86d5-81590142c9f7.png">

## 具体描述
 - TOU、社区行为准则、荣誉准则 三个链接均指向英文网站，建议替换为相应的中文网站
 - 自杀干预热线网站（美国境内）或 Befrienders.org，两个链接需要翻墙

**Comment by CallMeLog** [comment]
@sylviasun916

**Comment by scanfyu** [comment]
https://www.befrienders.org/
这个网站，貌似是不需要翻墙的，我这里尝试没问题。
但是是英文网站。

**Comment by scanfyu** [comment]
![image](https://user-images.githubusercontent.com/3198940/46901399-b7b93100-cee5-11e8-811b-ef7fae656b6a.png)

这里建议还是翻译一下（服务协议），会好一点。

**Comment by scanfyu** [comment]
![image](https://user-images.githubusercontent.com/3198940/46901411-d9b2b380-cee5-11e8-889d-3659368a6e6c.png)

逻辑上应当换行。

**Comment by sylviasun916** [comment]
关于翻译添加与换行，已修改，感谢反馈！ 

关于英文链接 @UdacityShuwenLiu @ChengGoooo  可不可以看一下哦？ 感谢！

**Comment by ChengGoooo** [comment]
同 #3
