### ISSUE TITLE
自然语言运算 > 评判标准 > 9. 精度 - 练习题答案翻译缺失

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#51]
## 课程导航+地址
自然语言运算 > 评判标准 > [9. 精度](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/dd22bf82-f166-4355-b53f-98c482f63699)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/qfBKrQvV6HVnrJfv206GeMZKGRvwW4hnrvnknd-8xpwdnucqQFBzr6ruzgZSeD0btBKkKJAn0ZEJTkxYJq0uQ2ZvyRhxsyt4ZiXAfWhcSGl8tyUN8sNBH6h11-l9frdoKvyo18TXwwKAcuXJqt3g9VtQQ2QSwqsqEs2ZlJzvIuV6-3tf0V_2ZjR61lkauj7DVJspHkN2rSvXElH5WBk50RBimy8BWFmloUxFbyHGnQ2BBhvtZ7tzyzCXoqBvthFcRHcUangJ4zpaYhdHknRsYzTtfPE8e9V7H615hSo9XXMwKNol9mVil3WkrSpoxuEl5b3DOa9up9j5JEp7-gt0E60jDyzDqR7E-jBzQqIidAsia-OECJopD5cHjA3OyEutbC6hNhRLyRHNw_eCAos_Q8KwMPE-QvHDr2aj4QOekHlr0cKiCQWWaZucl0GjP2ycmZjCji3Djd7V9_zOs0JvjXqYeRHLwbacZQBSLE9-_wkRMVAyX7gpgHNubvQBAZUEznr5GOoYPZndA4uotZl17Dvkx10NZyiIb0mAhf9H4j_U5m3vABPApGYGNpHwRnEYJgPTANpcXJu3cUD-MBvXm3Mi1c_ZYld34AzUgjWJc4D35JVUVhkykm974DYyDmE=w1200-h806-no">

## 具体描述
练习题中的截图并无翻译，我建议的翻译如下

精度 = 真阳性 / (真阳性 + 假阳性)

**Comment by yifangwang08** [comment]
感谢反馈！
