### ISSUE TITLE
自然语言运算 > 循环神经网络 > 8. 反向传播算法：理论 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#52]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [8. 反向传播算法：理论](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/6fbfd066-6907-4f72-98b8-c5743818fa06)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46923607-cf201900-cfce-11e8-8de3-45da1ef41ba9.png)

## 具体描述
视频1:42处字幕 通过每次从训练集中的一个输入展现网络，需改为 通过每次给神经网络提供一个训练集中的输入项

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
