### ISSUE TITLE
自然语言运算 > 评判标准 > 10. 召回率 - 练习题答案翻译缺失

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#53]
## 课程导航+地址
自然语言运算 > 评判标准 > [10. 召回率](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/9ac722df-8191-44df-b7f5-ef1732b2d053/concepts/944ae914-395f-4e65-a5f3-0ac24593c861)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Cjf-XVEWrDJWAAQjJHK3ahJTdP24IFFQSMaM6p3725LtnKBKzd5ZdCxQhWops4RaAtZjS24V_yLAOrg3VsFx47gEZE2qx5ctUXP5N1OhzAEl8Je3am0r_LevF2yEe2TqSbzoo7xgMX_BeiCEGfSoWh0HLu3FCtOCXnITKh-2Lx2sZKGcVhKYS0vTrM8n3pwHoifj1BNlJZeXAU5BJAXJpz2AFSSlD225LcBCWnUwJOX0rtZT3XXA5VTQ_CfNNheqVTx-AAGetV77THTlyJth3uLNKeqIHCGuvSHWQpF-rS9sr-kZeDbOmtnyVA_aYyqpmcOiy9RZWuRziICABVewMF8kK2owUOqdhtTFZ7EsIfQR-o_yDq4RQ83JjclRHhOz0qYHVPh6BJa1bEEvL72vilXH6L0Gi_jVDHuzp1zzYovpM69ovEG6h1AgqDmHKw7rFcMxwIWzTJbQ_00UzGmWb8j6lyfh5-po5MTuxDwcfnS6TrfB_KcpT203RGRMAqBpvQ1WZE855q9UFKPiOwRxnZbMnlxU0nOZv4Pv8f3MeaWvzoQ-6s9OJKPqsIsBqQk-xVmOjEkYKCoTOGFMgdY9OHtA4gDszHf7sDyZ_ZrJ_UwEsdiChZm8H-HUaMiI_Eg=w1188-h820-no">

## 具体描述
练习题中的截图并无翻译，我建议的翻译如下

召回率 = 真阳性 / (真阳性 + 假阴性)

**Comment by yifangwang08** [comment]
@ChengGoooo  该图片对应的链接（https://d17h27t6h515a5.cloudfront.net/topher/2017/June/5944cd88_recall-answer/recall-answer.png）在非 VPN 状态下无法打开

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个也是图片未翻译的问题~

**Comment by sylviasun916** [comment]
@ChengGoooo  @UdacityShuwenLiu  麻烦评估一下图片是否需要翻译哦？ 如同学建议所言，可否放在教室的哪个位置 ？ 谢谢！
