### ISSUE TITLE
自然语言处理入门 > 6.利用HMM进行词性标注 > [1. 简介]：翻译错位

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#54]
## 课程导航+地址
自然语言处理入门 > 6.利用HMM进行词性标注 > [1. 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/5483fffa-0272-4902-8aed-fc7d1818c8e5/concepts/aa550181-f1d2-46fe-af4a-e740dbf50093)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46929678-735b9b80-d073-11e8-85f8-f450d017daa0.png)
![image](https://user-images.githubusercontent.com/3198940/46929685-79517c80-d073-11e8-95d6-b0c7d770069b.png)

## 具体描述
视频13s处字幕，需改为：
这些模型对一些应用非常有用，
诸如语法和拼写检查器。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
