### ISSUE TITLE
自然语言处理入门 > 6.利用HMM进行词性标注 > > [2. 词性标注]：部分字幕未翻译

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#55]
## 课程导航+地址
自然语言处理入门 > 6.利用HMM进行词性标注 > > [2. 词性标注](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/5483fffa-0272-4902-8aed-fc7d1818c8e5/concepts/eef59e6f-a843-4f56-a0a8-e9141ed9503f)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46929859-9f2b5100-d074-11e8-8aff-93092c192cf9.png)

## 具体描述
视频24s处字幕部分缺失，需改为：
对于这个句子，Mary是名词，had是动词

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
