### ISSUE TITLE
自然语言运算 > 循环神经网络 > 17. 基于时间的反向传播算法 第一部分 图片注释

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#56]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [17. 基于时间的反向传播算法 第一部分](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/c872c9ec-18a9-4e3c-840c-b9fc85c93641)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46930599-656a3400-cffb-11e8-9965-251ef961d016.png)

## 具体描述
折叠模型中的梯度思考

不知道原文是怎样的 但读起来会感觉有些奇怪

折叠模型中的梯度

感觉就足够了

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
