### ISSUE TITLE
自然语言运算 > 循环神经网络 > 18. 基于时间的反向传播算法 第二部分 字幕及注释翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#57]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [18. 基于时间的反向传播算法 第二部分](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/ab9dd7dd-26fd-4ff6-8127-2665c9d4177d)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46931156-c5aea500-cffe-11e8-96cf-a32a857cc5ed.png)

## 具体描述
视频29s处字幕 
> 权重矩阵Wy连接这个数据和输出        

需改为 “权重矩阵Wy连接这个状态和输出”

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46931262-4bcaeb80-cfff-11e8-9cb2-fed214d62f87.png)

## 具体描述
> 如果仔细观察方程式2、3和4     

应改为 “如果仔细观察方程式38、39 和 40”
>公式6 考虑了    

应改为 “方程式42 考虑了”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
