### ISSUE TITLE
自然语言运算 > 循环神经网络 > 19. 基于时间的反向传播算法 第三部分 公式标记错误

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#58]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [19. 基于时间的反向传播算法 第三部分](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/e8aae31b-d77c-416c-82d7-82774154950e)

## 截图
> 这个例子中，我们需要考虑三个时间步长，所以我们累加了三个偏导数进行计算。一般来说，我们可以追溯多个时间步长。如果仔细观察方程式1、2和3，你将再次注意到一种模式。

## 具体描述
> 如果仔细观察方程式1、2和3      

应该改为 “如果仔细观察方程式 43、44 和 45”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
