### ISSUE TITLE
自然语言运算 > 循环神经网络 > 23. 更多数学知识 公式注释错误

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#59]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [23. 更多数学知识](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/593835fd-09a7-44a3-a1fc-56dadb02b2ca)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46932423-871be900-d004-11e8-98c3-815be70a55ef.png)

## 具体描述
> 方程式49: 调整Ws时基于时间的反向传播算法计算     

应改为 “方程式49: 调整Wx时基于时间的反向传播算法计算”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
