### ISSUE TITLE
1.自然语言处理入门 > 课程1.欢迎学习自然语言处理课程 >【4.课程计划】> 链接指向英文网站导致无权限访问

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#6]
## 课程导航+地址
例子：1.自然语言处理入门 > 课程1.欢迎学习自然语言处理课程 > [4.课程计划](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/b1084f71-9949-4439-93e6-1550d86ce1e9/concepts/562f115a-e979-49df-9c21-d72ba1fb3791)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46871923-40dc5380-ce65-11e8-8aa5-c042a41c10e5.png">

## 具体描述
课程链接均指向英文网站，导致没有权限打开对应的课程小节

@sylviasun916

**Comment by scanfyu** [comment]
![image](https://user-images.githubusercontent.com/3198940/46901420-0ebf0600-cee6-11e8-885e-a6e8917cd287.png)

这张图片原则上应该也要翻译的吧。

**Comment by scanfyu** [comment]
同CallMeLog反馈问题：

截图：
![image](https://user-images.githubusercontent.com/3198940/46901441-68273500-cee6-11e8-8bc2-9c5375af9f33.png)

具体描述：（跳转后）
![image](https://user-images.githubusercontent.com/3198940/46901443-7bd29b80-cee6-11e8-91d0-456e03ad121f.png)

**Comment by sylviasun916** [comment]
Hi @ChengGoooo  谷哥，这里的图片我们教室暂时不支持翻译哦，有没有可能通过别的方式展现给学员同样的内容呢？ 感谢！

**Comment by ChengGoooo** [comment]
同 #3 
已删除
