### ISSUE TITLE
自然语言运算 > 循环神经网络 > 24. 循环神经网络总结 字幕翻译及公式编号

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#60]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [24. 循环神经网络总结](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/d4a9bba6-9784-441e-b021-5510a14b46d4)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46933082-6012e680-d007-11e8-9c87-1a98cd83b0fc.png)

## 具体描述
视频1:45处字幕
> 我们选择多个批次    

应改为 “我们选择小批量法”

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46933157-af591700-d007-11e8-951e-553925e55da5.png)

## 具体描述
> 在方程式_51_和_52_    

应该改为 "在方程式 59 和 60"

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，我在字幕包里没找到截图1里的字幕文件，麻烦你看一下吧。其中截图2里的问题我已经改好了

**Comment by sylviasun916** [comment]
@yifangwang08  截图1 的字幕已修改好，感谢奕方！

该issue 已修改好，感谢反馈！
