### ISSUE TITLE
自然语言运算 > 长短期记忆网络(LSTM) > 8. 应用门 幻灯片错误

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#63]
## 课程导航+地址
自然语言运算 > 长短期记忆网络(LSTM) > [8. 应用门](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/1c0c804d-f928-4a3c-ae44-b62699a8b1ec/concepts/0cf688e2-19b3-4e72-848a-49eeb90bd948)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46934535-f0075f00-d00c-11e8-92cb-1bf251fc4417.png)

## 具体描述
视频27s处幻灯片错误 
> New Long Term Memory

应改为 New Short Term Memory

另外 在翻译 Use Gate 时 有时使用 **应用门** 有时用的是 **使用门**
两种翻译都可以接受 但是希望可以保持前后一致

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，这里面提到的幻灯片的错误麻烦你看一下是否存在问题

**Comment by UdacityShuwenLiu** [comment]
已修复
