### ISSUE TITLE
自然语言运算 > 情感分析 > 1. 简介 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#64]
## 课程导航+地址
自然语言运算 > 情感分析 > [1. 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/462b1b98-282a-4233-8e2a-f0b5731512e1)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46935216-6016e480-d00f-11e8-80fd-e467c68f8181.png)

## 具体描述
视频52s处字幕
> 并使用递归神经网络

在以前的课程中一直使用的是 循环神经网络 希望最好可以在专用术语的翻译上保持前后一致
建议直接使用缩写 “并使用RNN”

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46935224-673df280-d00f-11e8-9fdb-6deba8a65b2f.png)

## 具体描述
视频1:00处字幕
> 找到关于 RNN 和 LSDM 

需改为 “找到关于 RNN 和 LSTM”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
