### ISSUE TITLE
自然语言运算 > 情感分析 > 5. 利用 RNN 进行情感分析 链接问题

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#65]
## 课程导航+地址
自然语言运算 > 情感分析 > [5. 利用 RNN 进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/5d87edd4-2f79-4fd8-9e34-f21118ec7b29)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46936106-1da2d700-d012-11e8-9d94-929a11a9a6f9.png)

## 具体描述
这两个链接指向的都是 `nd892` 而不是 `nd892-cn` 的资源

**Comment by UdacityShuwenLiu** [comment]
似乎已经被解决，close了哦～感谢反馈
