### ISSUE TITLE
3. 自然语言交流>(选修课) Alexa历史技能>4.任务

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#67]
## 课程导航+地址
自然语言交流>（选修课）Alexa历史技能  [4.任务](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/2fa4cc08-d608-4b97-b87f-5c511e62c8c3/concepts/1abf8296-2751-4c1d-8d5f-078bf3bfa9e6)

## 具体描述
页面中所有的超链接无效，page cannot be found

## 截图
![default](https://user-images.githubusercontent.com/13103405/46948166-cca1ea00-d0c8-11e8-8208-fe88a72b6b90.png)

## 具体描述
这里的“历史事实”和“太空事实”翻译使人困惑

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，这里面提到的翻译困惑以及链接失效问题麻烦你看一下

**Comment by UdacityShuwenLiu** [comment]
已将相关课程隐去，感谢反馈
