### ISSUE TITLE
3. 自然语言交流>(选修课) Alexa历史技能>2. 开始

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#68]
## 课程导航+地址
自然语言交流>2 （选修）Alexa [2. 开始](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/2fa4cc08-d608-4b97-b87f-5c511e62c8c3/concepts/0170fd5e-c3e0-4a65-85f2-628b105dd9a5)

## 截图 1
![图一](https://user-images.githubusercontent.com/13103405/46947680-551f8b00-d0c7-11e8-9530-8fe4662e6ce0.png)

## 具体描述
“并构建基于此项目的项目”表达不清

## 截图 2
![](https://user-images.githubusercontent.com/13103405/46947640-2f928180-d0c7-11e8-9dbb-a3199241bb0f.png)

## 具体描述
图中超链接无效

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，截图2 反映的链接打不开，我怀疑是不是账户权限导致的（我的账户可以打开链接，跳到的是课程英文版的界面）或者是链接放错了？麻烦你看一下

**Comment by UdacityShuwenLiu** [comment]
已修复，感谢反馈
