### ISSUE TITLE
3. 自然语言交流>(选修课) Alexa 历史技能>3. 部署技能

### ISSUE THREAD

**Issue by Usief** [udacity/cn-nlp-issue-report#69]
## 课程导航+地址
例子：自然语言交流> (选修课) Alexa 历史技能[3. 部署技能](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/306e899a-9ea3-4b67-8b1d-11b3931fe6b6/modules/21b617e4-5948-4145-8a1d-ba5719e8ae52/lessons/2fa4cc08-d608-4b97-b87f-5c511e62c8c3/concepts/c21d552e-e5b2-49a3-80e3-b1ed1c02b93d)

## 截图
![default](https://user-images.githubusercontent.com/13103405/46948055-8482c780-d0c8-11e8-84e5-a98131f59e7b.png)

## 具体描述
这里黄箭头所指内容，翻译应该一致。最好统一成“Alexa Skills Kit”

**Comment by yifangwang08** [comment]
感谢反馈~我们已对该建议进行了修改~
