### ISSUE TITLE
1.自然语言处理入门 > 课程3.自然语言处理简介 >【7.语境最重要】> 翻译问题

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#7]
## 课程导航+地址
例子：1.自然语言处理入门 > 课程3.自然语言处理简介 > [7.语境最重要](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/e79dd351-a1d3-426d-a259-bf8cf9a26a98/concepts/3733d4b0-948d-41f2-9350-7cdab3dfb63d)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46874453-c9f68900-ce6b-11e8-9f83-5e85326b0f25.png">

## 具体描述
视频42s处字幕：But there is a bigger challenge that makes NLP harder than you think.
翻译：不过让自然语言处理的难度超出你想象 存在越大的挑战

应改为：不过存在更大的挑战让自然语言处理的难度超出你想象

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
