### ISSUE TITLE
1.自然语言处理入门 > 课程6.利用HMM进行词性标注 >【2.词性标注】> 字幕缺失问题

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#70]
## 课程导航+地址
例子：1.自然语言处理入门 > 课程6.利用HMM进行词性标注 > [2.词性标注](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/5483fffa-0272-4902-8aed-fc7d1818c8e5/concepts/eef59e6f-a843-4f56-a0a8-e9141ed9503f)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46955190-eb9e7d00-d0c4-11e8-8cef-75d830141b39.png">

## 具体描述
视频21s处字幕 the tags are noun for  Mary, verb for had  未翻译

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
