### ISSUE TITLE
1.自然语言处理入门 > 课程6.利用HMM进行词性标注 >【7.练习：有多少条路径】> 字幕不当

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#71]
## 课程导航+地址
例子：1.自然语言处理入门 > 课程6.利用HMM进行词性标注 > [7.练习：有多少条路径](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/5483fffa-0272-4902-8aed-fc7d1818c8e5/concepts/74b782f8-374c-4c6f-b696-152f358dc40a)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46958566-abdb9380-d0cc-11e8-8f30-9a25e901af91.png">

## 具体描述
视频2m20s处字幕  We have the parts of speech noun, modal verb, noun
按照课程内容应该为：We have the parts of speech noun, modal, verb, noun
中文翻译正确，英文字母 modal verb 应为 modal，verb

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
