### ISSUE TITLE
自然语言运算 > 情感分析 > 3. Notebook：利用常规分类器进行情感分析 实验翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#73]
## 课程导航+地址
自然语言运算 > 情感分析 > [3. Notebook：利用常规分类器进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/648d1e34-9ddc-45d7-8e25-c51aeef92640#)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46991923-b4c46900-d0bc-11e8-847b-35bf329881b7.png)

## 具体描述
lab 未翻译 应该指向 `sentiment_analysis-zh.ipynb` 

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46991990-f9500480-d0bc-11e8-81a6-0dbfb3478f32.png)

## 具体描述
同时 可以考虑把代码注释也翻译一下 比如
> ```# TODO: Combine positive and negative reviews and labels```    

```# TODO：合并正面与负面的评论与标签```

**Comment by yifangwang08** [comment]
感谢反馈！
