### ISSUE TITLE
自然语言运算 > 情感分析 > 6. Notebook：利用 RNN 进行情感分析 实验资源

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#74]
## 课程导航+地址
自然语言运算 > 情感分析 > [6. Notebook：利用 RNN 进行情感分析](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/803aa80a-5caa-4fc9-934f-3357d1593616/concepts/712c0605-2d22-48af-b60a-5dbd39895c19#)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46992204-ca865e00-d0bd-11e8-9e55-3480b057ef7d.png)

## 具体描述
应该指向中文的实验资源 `rnn_sentiment_analysis-zh.ipynb`

**Comment by yifangwang08** [comment]
感谢反馈！
