### ISSUE TITLE
自然语言运算 > 1.特征提取与嵌入 > [1. 特征提取]：字幕错位

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#75]
## 课程导航+地址
自然语言运算 > 1.特征提取与嵌入 > [1. 特征提取](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/dda7d28e-d9bc-47dc-9c34-5e0cccafb829)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46992205-85a10c80-d13b-11e8-9c02-f2b7cf0ab3c9.png)
![image](https://user-images.githubusercontent.com/3198940/46992250-b7b26e80-d13b-11e8-8a48-ce4467165ab1.png)

## 具体描述
视频15s处字幕需改为：
这些统计可以通过以下方式来提升效果
即通过TF-IDF方案分配适当权重

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
