### ISSUE TITLE
自然语言运算 > 序列到序列 > 3. 介绍 Jay 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#76]
## 课程导航+地址
自然语言运算 > 序列到序列 > [3. 介绍 Jay](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/e926d323-9f84-4b2c-bbeb-0fa8e56c0c43/concepts/ab43e169-e8fb-49c4-b7ca-b677cfa29445)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46992443-f229f600-d0be-11e8-91e7-d42ab58d48db.png)

## 具体描述
视频1:36s处字幕
> 负载处理序列数据    

应该改为 “负责处理序列数据”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
