### ISSUE TITLE
自然语言运算 > 1.特征提取与嵌入 > [2. 词袋]：字幕错位

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#77]
## 课程导航+地址
自然语言运算 > 1.特征提取与嵌入 > [2. 词袋](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/9ca58996-a428-41d4-8e2c-81233d87e988)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46992634-a10d1700-d13d-11e8-94a0-9d457a2d8a32.png)
![image](https://user-images.githubusercontent.com/3198940/46992663-c39f3000-d13d-11e8-805d-6eb2c1ed5201.png)

## 具体描述
视频1m47s处字幕，需改为：
展现了其中的关系：所处行位置的文档，
和所处列位置的词或词条。

**Comment by yifangwang08** [comment]
感谢反馈！
