### ISSUE TITLE
自然语言运算 > 1.特征提取与嵌入 > [2. 词袋]：字幕错误

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#78]
## 课程导航+地址
自然语言运算 > 1.特征提取与嵌入 > [2. 词袋](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/9ca58996-a428-41d4-8e2c-81233d87e988)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46992885-eda52200-d13e-11e8-841b-cd0b919fe1a7.png)

## 具体描述
视频2m22s处字幕，应该改为：
也就是对应元素的积的总和。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
