### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 5. 练习 注意力概述 翻译用词

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#79]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [5. 练习 注意力概述](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/c49cb14c-074a-4429-990e-5150c9e75c53)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46993445-1b995080-d0c4-11e8-8fc8-2dadbafdecf2.png)

## 具体描述
> 假 - 序列到序列模型的原理是一次将输入序列的一个元素馈送到编码器中

假 - 序列到序列模型的原理是一次将输入序列的一个元素输送到编码器中 

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46993454-27851280-d0c4-11e8-81ce-853880abdade.png)

## 具体描述
> 语境矩阵的大小因输入序列而变化

语境矩阵的大小随输入序列而变化

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
