### ISSUE TITLE
1.自然语言处理入门 > 课程2.优达学城提供的学习支持 > [1. 学习支持]：Markdown翻译

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#8]
## 课程导航+地址
1.自然语言处理入门 > 课程2.优达学城提供的学习支持 > [1. 学习支持](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/92db2bf4-9d66-4227-8cf7-e502d5acfcd4/concepts/16c1aba8-6552-4e0e-95a2-1c72a260e807)

## 截图
![image](https://user-images.githubusercontent.com/3198940/46901863-f18e3580-ceed-11e8-93a5-cbe9b991c6aa.png)

## 具体描述
1. 国内一般 “软件工程师“ 都叫开发的吧，这里 是不是应该翻译为 “小型开发团队”更为合适。
2. “代理”出现在这里感觉比较奇怪，我读到这里会产生一定的困惑。代理是什么？

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/46902016-45018300-cef0-11e8-836b-440d4f81ac90.png)

## 具体描述
“设置”这个词比较奇怪，“提供”感觉会好一点。

**Comment by ChengGoooo** [comment]
中文版中我们去掉了美国的服务说明，添加了中文的学前指南。
