### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 7. 注意力编码器和解码器 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#80]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [7. 注意力编码器和解码器
](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/43fb2e4f-de7c-4fc8-a955-1f6245ce5eb6)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46993938-e8a48c00-d0c6-11e8-838d-e55100ef0c16.png)

## 具体描述
视频1:35处字幕
> 解码器现在查看了输出单词和注意力语境向量

解码器现在查看了输入单词和注意力语境向量

## 截图 2
![image](https://user-images.githubusercontent.com/12591144/46993944-efcb9a00-d0c6-11e8-9a22-76f106329103.png)

## 具体描述
视频1:49处字幕
> 并输出输出序列的第一个单词

并生成输出序列的第一个单词

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
