### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 9. Bahdanau 注意力与 Luong 注意力 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#81]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [9. Bahdanau 注意力与 Luong 注意力](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/ffd9108d-7cfb-4327-a4f2-a250ba8d16db)

## 截图
![image](https://user-images.githubusercontent.com/12591144/46994341-e7745e80-d0c8-11e8-86a1-ea64c9630cf3.png)

## 具体描述
视频1:39处字幕
> 解码器是双向RNN

编码器是双向RNN

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
