### ISSUE TITLE
自然语言运算 > 循环神经网络 > 5. 前馈神经网络 - 标题建议

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#82]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [5. 前馈神经网络](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/ebec6246-752c-49ef-bf74-423b8c3683f3)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/9aZMXlA5yEuHaq6MBnHqWQBjUTZ2h-oNGORb3_t5IGrTdRT__9eeJbRNzQLOo5fdwqGJUTriDq5QmagZbgugBqxG5NTnZ8gSSk9yKmBBN-JprLde4fftnBNDxhzT2pEeslCRH4rFsIpNB_VwxNO2_iOPBarworE5x6okCdZntbkRk2UK5kYRdg26pwr4nxef0EcnonXlvmCdpIrIZ2XgsV9ZeBf_iKyCBwEpQqZB0DfaGDfnGc9FQ8UfxPinxYahTOaF4xtrzFM7yMz1wKwUIUajrlKZxgUBtpIkJMOpQMCpSa8Omdk3Ni9aupyYREF0UapdaeDIa664fFUH-K1UgbOLTMQISv7wchQVfU6A6pxwmLdVikKLRYIZYYxzAigckxcSjpEjqIgZQiaf3tXnGkIZngA5kNGZXJzhETRaZ196uh9LBh1BCvFWPE7XLSDT973yJCBPicwsIBIGHoiU57URNjgo5WD0Ddlrhh3NGsFXpBwys4Y9TshbIU7QCBWtV-YkZ0FkGbi_iC5qhB4tPKzPSgQxgmtB4BeeIouZKQkO2lHrkaAzBmrvvzPI49hkRhfHpsbFiEgbNKuqlBYpjvh7A2e8qxjmS0Y46aEjz84NJmssndyABLsFSFtpTO4=w1446-h272-no">

## 具体描述
根据内容，标题建议修正为“前馈神经网络：复习”

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  淑雯，麻烦你看下这个标题需要改吗？

**Comment by ChengGoooo** [comment]
@yifangwang08 这种问题根据文字内容理解直接修改就好了。

我改成了“回顾”。
