### ISSUE TITLE
1.自然语言处理入门 > 项目：词性标注 >【1.简介】> 链接

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#83]
## 课程导航+地址
1.自然语言处理入门 > 项目：词性标注 > [1. 简介](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/824ac543-87d4-4677-8c47-d5029e7effde/modules/37b5992b-97d2-4170-99fa-25330196e51f/lessons/e4da24c2-5713-4802-8066-542fc4210adb/concepts/4dc4052d-e3bf-4a58-b20f-e84518a82660)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/46998935-a9be1700-d156-11e8-80cc-e0b8325ad996.png">

## 具体描述
评估标准：https://review.udacity.com/#!/rubrics/1429/view
此链接为英文页面，是否有中文页面

**Comment by ChengGoooo** [comment]
@CallMeLog 你留了一个 nd113-cn 的链接😂

**Comment by CallMeLog** [comment]
> @CallMeLog 你留了一个 nd113-cn 的链接😂

忘记改了，哈哈

> @CallMeLog 你留了一个 nd113-cn 的链接😂

已改，哈哈哈

**Comment by UdacityShuwenLiu** [comment]
已修复，感谢反馈
