### ISSUE TITLE
2.自然语言运算 > 1.特征提取和嵌入 >【8.深度学习的嵌入】> 字幕

### ISSUE THREAD

**Issue by CallMeLog** [udacity/cn-nlp-issue-report#88]
## 课程导航+地址
例子：2.自然语言运算 > 1.特征提取和嵌入 > [8.深度学习的嵌入](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/46c8506d-50a1-4de8-bd1c-18b47af15b20)

## 截图
<img width="1212" alt="demo" src="https://user-images.githubusercontent.com/33828759/47005711-e5f97380-d166-11e8-9173-5d99af729d6b.png">

## 具体描述
视频 3m29s 处英文字幕 an LP，需改为 NLP

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
