### ISSUE TITLE
纳米学位简介翻译缺失

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#9]
## 课程导航+地址
我的课程 > 纳米学位项目卡片

## 截图
![image](https://user-images.githubusercontent.com/12591144/46901887-910ce300-ce70-11e8-9ace-93fc0d01f9fb.png)

## 具体描述
简介内容应该有翻译 大概像下面这样的吧

熟练掌握相关技能，可以让电脑理解，处理，以及操控人类语言。
建立基于实时数据的模型，动手体验情感分析、机器翻译等项目。

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，我的帐号看不到这个页面，麻烦你看一下

**Comment by sylviasun916** [comment]
已修改 感谢反馈！你的推荐翻译很不错！
