### ISSUE TITLE
自然语言运算 > 1.特征提取与嵌入 > [6. Word2Vec]：字幕错位

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#90]
## 课程导航+地址
自然语言运算 > 1.特征提取与嵌入 > [6. Word2Vec](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/f9e23dbe-f3ad-4c3a-b098-d0cec8caa6a6)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47062481-e3e7f100-d208-11e8-904f-ec28c2dd6f49.png)
![image](https://user-images.githubusercontent.com/3198940/47062486-e9ddd200-d208-11e8-83f6-65aa5f6586cd.png)

## 具体描述
视频1m22s处字幕：
由于每个词的意义分布在向量中
这种词表示法非常稳健

需改为：
产生一个非常健壮的词表示
这是由于每个词的意义是分布在向量之中的

**Comment by sylviasun916** [comment]
已修改，感谢反馈！
