### ISSUE TITLE
自然语言运算 > 1.特征提取与嵌入 > [7. GloVe]：英文字幕错误

### ISSUE THREAD

**Issue by scanfyu** [udacity/cn-nlp-issue-report#91]
## 课程导航+地址
自然语言运算 > 1.特征提取与嵌入 > [7. GloVe](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/103de6ce-e373-4bdb-8ca4-fcd0ef82dd68/concepts/f3efc741-c87f-4af2-99fd-cc0b82ccc2f5)

## 截图
![image](https://user-images.githubusercontent.com/3198940/47062727-4097db80-d20a-11e8-80cf-00453bf82e38.png)

## 具体描述
视频9s处字幕“world”，需改为"word"。

**Comment by scanfyu** [comment]
## 截图
![image](https://user-images.githubusercontent.com/3198940/47062838-f06d4900-d20a-11e8-843c-1a417c49614e.png)
![image](https://user-images.githubusercontent.com/3198940/47062915-77222600-d20b-11e8-9da9-89852c164244.png)

## 具体描述
视频26s处字幕，需修改

**Comment by sylviasun916** [comment]
Hi 第一个 9s 英文字幕已修改； 第二个不太理解，需要 @UdacityShuwenLiu CM 的专业学科看一下哦，具体需要怎么修改哦？ 感谢！

**Comment by sylviasun916** [comment]
英文字幕已根据原音进行修改，感谢反馈！
