### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 15. 其他注意力方法 字幕翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#92]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [15. 其他注意力方法](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/59deedb9-cbd8-4799-a3dc-fe2eec30336a)

## 截图
![image](https://user-images.githubusercontent.com/12591144/47062976-0ab51180-d18e-11e8-8a1f-74c30b2c428e.png)

## 具体描述
视频1:06处字幕
> 可以用单独的CPU处理每个元素

可以用单独的GPU处理每个元素

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
