### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 16. Transformer 和自注意力 链接缺失

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#93]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [16. Transformer 和自注意力](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/48b7d2a3-2b9c-46fa-8491-ac070688a758)

## 截图
![image](https://user-images.githubusercontent.com/12591144/47063197-0b9a7300-d18f-11e8-8c41-a4c2e4d14c1a.png)

## 具体描述
视频4:18处字幕
> 我们提供了该论文和一些实现的链接

视频下方没有找到相关链接

**Comment by UdacityShuwenLiu** [comment]
已写上注释
