### ISSUE TITLE
自然语言运算 > 深度学习注意力机制 > 17. Notebook：注意力基础知识 实验链接错误

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#94]
## 课程导航+地址
自然语言运算 > 深度学习注意力机制 > [17. Notebook：注意力基础知识](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/df138c4b-4ca9-4ac6-9d9f-2bcb42f6768b/concepts/f3030c2f-2662-4d89-8938-578c7473066f#)

## 截图
![image](https://user-images.githubusercontent.com/12591144/47063506-1efa0e00-d190-11e8-933e-095e0c309fab.png)

## 具体描述
应该指向中文版的 notebook `Attention%20Basics-zh.ipynb`

**Comment by yifangwang08** [comment]
感谢反馈！
