### ISSUE TITLE
自然语言运算 > RNN Keras Lab > 2. 机器翻译 图片标注

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#95]
## 课程导航+地址
自然语言运算 > RNN Keras Lab > [2. 机器翻译](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/06c89f82-2fd1-409e-9d09-e785d32036d7/concepts/3ea3dcb6-7ee0-45c0-955d-5bec5c9f3a25)

## 截图
![image](https://user-images.githubusercontent.com/12591144/47064071-c6784000-d192-11e8-9ab3-767a3031eabe.png)

## 具体描述
可以将这张图的 嵌入层 递归层 以及 密集层 用中文标注一下吗
其他的可以不用翻译 但是感觉这三个会对下文的理解有帮助

**Comment by yifangwang08** [comment]
@UdacityShuwenLiu  这里面的翻译涉及到专业词，麻烦你看一下~或者你评估下看需不要添加中文标注~
