### ISSUE TITLE
自然语言运算 > 循环神经网络 > 5. 前馈神经网络 - 字幕翻译

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#96]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [5. 前馈神经网络](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/ebec6246-752c-49ef-bf74-423b8c3683f3)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/NWK4xwo8TsscQYdZaH9qzyeu_TWd1TSWad9z92YN8ER46iL4WaCDwZ_DmEVXliEa2aZIbCqvkbISTylK1uTRBJb_DTOh0MUb4YEjuE6PerGgafRGMvAHTykuwpKNrK7BhtWboBkL29Txpnug8HOBeQ4H7kkZAwYeKV98OpyC_4ZYI21PmSOj51lc6Ll1NxOtGkLC4yG8GDJvkIy3EBj1R6owFWK48AwgvYuTYCT8SXWtKaevePhVDJLcLQI-keFBBuH4bazNZKAxEavdcoydZviQCGMAvvTpUKRYxE6792po0wsdvrMierXh18DcXesDNeADz7tBJE5xgHuEPaoJl5_jK_mKqJrULoxrwsnE6sJeSuYIp-vCOu4-wIK8QPDJU2CknjXyBp1J02JZhVvFtdaESEipAH12LY91C979H0Ev0c9vof6I2FDMVtGeimjzHeiu8mVYan2FvoLJb_jwpWF_mNXTl6H4CZ_hpNBJkbuTdt1hvnCrEKNQvDM5R5oDaYmjWJD-dTfcJTpl3CYX8cdH1NTA9KEgzrMZ-PrCzOJjcHqWz2xDT6saeTIXGZhxEjR6he0aUx1EymQXGVIh7BPk6353OFtlLp0mv3yDFoCkW8_k6n4CwLXhtvbCh54=w1592-h914-no">

<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/5zGbcn8OIlX8Y_cEMZs0Ma9KGAoaLPaBHbVbyrctS-dC5PyEVWhGMiitM_Xiz_izpo1JGr_MuN-m4jr0qvceumTT5ftnJtdL1O3fbRv8KC-dsM2EWzoiSiA8FnHnL077HIYcjK1BeCOsvcZWrV1XIg_WaNPo-OVPo1LUY7EBy0TdDrBNBFnUA7O-xm3rOlfmcyOlA-e2FsV_5use5ShOSj3vomMxWhsoUAxsg8f_gbumesdB90G0VL9fq7J9rPvhx3AByX-6oYd_cOs19xlHUrEiB3UdORu-Kh9giFd43MGohee-lUVKzQAHxqJlC0V_jxPtsyOrLNevf-65v0o7f160_-tSNr9W_93Kbp5op48wMkFOAbSR5c7BJvT9TYa23I1VSWu4i5Wef1uU2ZcpuozDOZ_98UkLoWYuYdqOGdu5vMhsydj_nq1XZzN8--og07D5J9Ol7iqlxBRYE7UFOAkJj_DKFlTznpTSmtDqXU0ndCRKXEDT7uLloltSXOToGsdhRDsJPvTtBY-OATSqDi5IJbASIaMKH1E8BeCkrB5EdZ1XDd_AjUZCoWB0J4ijNREA9xVLu3UWjcOzhbJkIrikUu0e39t-nu9P3STPxQAOkjLhPYf30QOluqL4j1I=w1582-h906-no">

## 具体描述
视频15s~16s处字幕「我们会提醒自己使用它的」和 「原因 时间和方式」这两句的断词不易阅读，建议改为「我们会提醒自己使用它的原因，时机和方式」

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/Q5MY56Cy4Yd8nkwKIFgzxjEMckmhiTTf3swPOY6EgyxykcTWmoILaEr3rhFsm3Xxn9xiAbx6ecqNDvPuQdZuv86pu-U8KkxqpPtzi0KDNbq9dHAhluA90JpReG29ZvXw8BQKJSlHrQqSi0-uJRUzCyawwNFnsvGwgRf-Mon3NuJQf3-U7zrHSFz8DuTxeNquZGpGx4jqPcFbx0E7okpmSOED9hGFxGgmOVSEOm4IU1rDaNequvOAVy9qd5HV6ZHCw_08HRVr44_W-dWd8hTEZ-iTASkxTK9o9siFmi3gnzlLoou9-NyCjPpDoS7y5xDX_M2hGY9BKEbEKf7ZvJOb6R9RL5bLEKOV_YiXMO9M9GiR_HpA0ySNBhNxH3vYk3xA9OeLe5kWdHLVcktWarBD9BPJLvQq6tV0VK18khGQtf9Fcmr4c2xJpyujwL6sMHcgAnXX_nvP4cUw2yalbMGsMBJpSGAiJJQYK4XhlFL6Ss_ScTEkgP8XFLYU2VnyCA452hsz-8GS8aTZmXMpPspVLVB77J_8Ai9KcE64klRKAyRbMkXXLiPxvi2pWwkruQkQJluRSscJdoneg2wm-MlK3rgwP91o-Q1JEJJnO4EyoOXTyQ5Xe0HBHFAJxbdXQTg=w1598-h916-no">

## 具体描述
视频4m26s处字幕「在估值阶段」，应改为「在评估阶段」。

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/MA8i64KHTEGJ1UUe3mC_WF6EF0qOg-dJ3WsjazIrBtvFPyS8PCE1jrLUtCusRgSHY0sb6XricO0spWG9nCxv3H7l56yHCa9pVoTMGMQ2H5WGUuS00lBKKP6YNeRC8isqfWMYF_iew35ncRH0T7hdSMiwV4tF1rmXl7l32IxoOJozv5WPHuulrFWlPomGXmTrd2aqIjp_BtoKoRUsBcfZr7udC_Lz3o4jQwSXKuVqottS4KeR1yCmCzDixy8SSpCbNAai1zXWvIqprJ7uohacJlhmGqpitxWLQH7JF2YMK5cAWFTNXhFpUnLBGDGIX3K3iTsE_jnpUMuEqotg2L-Ni_K88OammZTan5OH-j2wiCEAI9cSvWqbfO_g-2_T4ek7HQIO47UTRGhH8zCGmSoi8tMXTlvzxMQ40e6lZk-EoahPoKyBXpOt6D-O1TphcSj_9XPXN9IcgM0WNUssSSbqQgXypaNbd79QOHLdYimNe2lVXM545j7nObO6QrUcJhmJI2UbH26E9s48UAdlFKbM4mbOGrbe0AuJZ3JT1626fOgdo7o788c40aAh0Ityzkp6CXAYek_TI38r-KqTtcnZA3x2C_9ySHOeX5Gz5nO0BWpNDbFTJMYHHo-Krb_TuZo=w1592-h1058-no">

## 具体描述
视频1m44s处字幕「我们知道可以使用人工神经网络 需要训练这个网络」和下方的注解不一致。

**Comment by YungChunLu** [comment]
## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/xlgrAa5CUJkAHTHQolaPnMRu2PziPRUCR6TR_gShA38MqAXhSnP3tMX9WxQqeyHXLSDVf44f-lTw1VDShyhBE8KTYWUuvqZKbfYgQy4BTjwxmm9Xw8nHaemWryfivtomRMxo5d_LC0G31oBRE1Oulh4s_piVU47GQE5Wky1J4l7xDMiuJaxY2aaJbMVQz89Aj2SNFfCK6yOjna3y7Nc9SM1ARKgY8H_InKksfS8wbpMFejGZPfYRtWj1spueM_rXygDYDGUZ-MzDezVGmfdIPXeDhMxWFkYKq3oxSTfMCA4ZfKY2rCbPY56Mptao1CfimJa-gOOWgSARyTe2tzlJ7cep822hMIe6-lkwYuVjI0-nv0AiTr3Ct-ICkbXxDLXfWjFIeWPV8BDDWtaHmjdn2K-u_f0_3yUStLsLnMQHMJ6fYbx5ndR6XvcTRDZTv0-3BWD22vLIAL9_vofifqa4nno02KUVXJ3tJzC5EP2faogO0P4Qbydm7MWYuO5jnIYZ7kJN_4y8kibBO23vI5T5QNNukUVokhe9cjWx6CFU5WeYyiyjdf8BjY_hHATql-is0wn_jQy4WmMgcHZpEtcxevUKP8HEIrVrPOIliF6zN07EE-RysKZKGLFDLvMfOCI=w1604-h920-no">

## 具体描述
视频2m50s处字幕「对比输出和正确的输出 可以向我们提供一个误差」，建议改为「对比系统的输出和正确的输出 可以向我们提供一个误差」。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
