### ISSUE TITLE
自然语言运算 > 项目：机器翻译 > 3. 自然语言处理机器翻译 Workspace 实验翻译

### ISSUE THREAD

**Issue by TianyuanC** [udacity/cn-nlp-issue-report#97]
## 课程导航+地址
自然语言运算 > 项目：机器翻译 > [3. 自然语言处理机器翻译 Workspace](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/beaa3a49-968e-41f9-8823-1f14f64048bc/lessons/30f31cf9-74bd-4764-a223-ea2967820ac7/concepts/b7226898-22d9-46ea-bafc-28f166c632ea#)

## 截图
![image](https://user-images.githubusercontent.com/12591144/47065278-42748700-d197-11e8-9fb5-e20cb3e3a47f.png)

## 具体描述
这个翻译实验好像没有翻译。。。

**Comment by UdacityShuwenLiu** [comment]
已修复
