### ISSUE TITLE
自然语言运算 > 循环神经网络 > 6. 前馈过程 - 链接建议

### ISSUE THREAD

**Issue by YungChunLu** [udacity/cn-nlp-issue-report#99]
## 课程导航+地址
自然语言运算 > 循环神经网络 > [6. 前馈过程](https://classroom.udacity.com/nanodegrees/nd892-cn/parts/859ab0d8-c073-45d8-9004-ac5297617457/modules/94a0d603-1dbf-4ae4-98fe-1bcd560e32e3/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/29a326a7-32b9-46bb-93aa-10a09acef7c0)

## 截图
<img width="1212" alt="demo" src="https://lh3.googleusercontent.com/EposDA3bePO6NRTM1dhTmCR8bElPQEf-36P7hmGYpgj4_DYbFk80U0_WMV_0OOnN521v3L9E7ARFIgJAQ4UVIdOGJSC9CObZWsyecVK_sPRmblQelCdEuTxh-1nH4wahHyWSUacxairjD4J9G1KrwOfoNyKIsQOGpYlCIRJlmMb_HmNuZuiNZQga8BORTq3ciCFUDWdl6fnYpee0j4N74XCbom-92GE-sWU7PsAGp0QGrhw2D6kLNvWFykTlxlIenuQMlLgmA4j3s3KR4JRqoNTrJSb1wvx-7wC4XFeSpprkkbaHesApg8xOLzD3xsMAr9aWuDTZw5DnlQPhg28jErpf1FOfWsepVja0g-p3zEjwQgFRf2oT6x8ceGJFKzvX04AKw0Rm-1XMJDcHp34DAReVUHS9Cjl9Weu3-J_4UwqRyLebGtCvllNX7slR8nMcXq67ADXauElCzmHE1m_L1THQaDw2hkaWf84m-aiQBo_WPmYI6gy9eHoWqPkyl2zdY2I9a6WM-JCH-6DnSu2hBDHTV1Hziazrp4h4VFHhClclnjnFLR5qh4hAdhMwdITA8gBiSopcc4KEdV5FoYpURxHfrbn-YQtcJ66tupasw_sY831TrorqHlYNuypeZeQ=w1466-h528-no">

## 具体描述
关于内文中的两条链接，建议直接放入Udacity自己开发的[基础线性代数课程](https://cn.udacity.com/course/linear-algebra-refresher-course--ud953-enterprise)

**Comment by yifangwang08** [comment]
感谢反馈！
